(()=>{'use strict';
/* FERMA PRO v43: editable layer feed norms + phase-based calculations. */
const n43=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const e43=v=>typeof E==='function'?E(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function lp43(day){return day<140?{name:'Вирощування',from:1,to:140}: {name:'Кладка',from:140,to:9999}}
function norm43(day){const p=lp43(day),rows=(C.phases||[]).filter(x=>x.kind==='layer');return rows.find(x=>x.name===p.name&&Number(x.from_day)===p.from)||null}
function rec43(b,date){if(!b)return 0;const d=Math.max(1,Math.floor((new Date(date+'T00:00:00')-new Date(b.placed_at+'T00:00:00'))/86400000)+1),p=norm43(d);return p?n43(p.recommended_feed_g_head):0}
function layerActual43(id,date){return (C.daily||[]).filter(x=>x.batch_id===id&&(!date||x.record_date===date)).reduce((s,x)=>s+n43(x.feed_kg),0)}
function layerNormTotal43(b,from,to){if(!b)return 0;let d0=Math.max(1,Math.floor((new Date((from||b.placed_at)+'T00:00:00')-new Date(b.placed_at+'T00:00:00'))/86400000)+1),d1=Math.max(d0,Math.floor((new Date((to||D())+'T00:00:00')-new Date(b.placed_at+'T00:00:00'))/86400000)+1);let total=0;for(let d=d0;d<=d1;d++){const p=norm43(d);if(p)total+=n43(p.recommended_feed_g_head)*heads(b)/1000}return total}
window.layerFeedNorm43=norm43;window.layerRecommended43=rec43;window.layerNormTotal43=layerNormTotal43;
window.layerNormForm43=async function(){if(!window.user)return;const rows=(C.phases||[]).filter(x=>x.kind==='layer'&&(x.name==='Вирощування'||x.name==='Кладка')).sort((a,b)=>a.sort_order-b.sort_order);const r1=rows.find(x=>x.name==='Вирощування'),r2=rows.find(x=>x.name==='Кладка');openModal(`<h3>🥚 Нормативи корму несучок</h3><p class="muted">Задайте норму корму в грамах на 1 голову за добу. Програма застосовує її автоматично до віку партії: <b>Вирощування 1–140</b> та <b>Кладка 140+</b>.</p><form id="layerNorm43" class="grid g2"><div class="field"><label>Вирощування, г/гол/день</label><input name="grow" type="number" min="0" step="0.1" value="${n43(r1?.recommended_feed_g_head)||''}" required></div><div class="field"><label>Кладка, г/гол/день</label><input name="lay" type="number" min="0" step="0.1" value="${n43(r2?.recommended_feed_g_head)||''}" required></div><div style="grid-column:1/-1" class="card"><b>Розрахунок:</b> норма × поточне поголів'я = потреба корму за день. Для періоду програма підсумовує норму по кожному дню.</div><button class="primary">Зберегти нормативи</button><button type="button" class="secondary" onclick="closeModal()">Скасувати</button></form>`);$('layerNorm43').onsubmit=async ev=>{ev.preventDefault();const vals=[['Вирощування',1,140,n43(ev.target.grow.value),1],['Кладка',140,9999,n43(ev.target.lay.value),2]];for(const v of vals){const old=(C.phases||[]).find(x=>x.kind==='layer'&&x.name===v[0]&&Number(x.from_day)===v[1]);let q;if(old)q=await db.from('feed_phases').update({recommended_feed_g_head:v[3],from_day:v[1],to_day:v[2],sort_order:v[4]}).eq('id',old.id).eq('user_id',user.id);else q=await db.from('feed_phases').insert({user_id:user.id,kind:'layer',name:v[0],from_day:v[1],to_day:v[2],sort_order:v[4],recommended_feed_g_head:v[3],recommended_weight_g:0,notes:v[0]==='Кладка'?'Кормова норма фази кладки 140+':'Кормова норма фази вирощування 1–140'});if(q.error)return alert('Помилка збереження: '+q.error.message)}await load();closeModal();alert('Нормативи корму збережено.')}};
const oldLayers43=window.layers;window.layers=function(){if(typeof oldLayers43==='function')oldLayers43();setTimeout(()=>{const c=document.querySelector('#content');if(!c||c.querySelector('[data-layernorm43]'))return;const d=document.createElement('div');d.dataset.layernorm43='1';d.className='card section';d.innerHTML='<div class="row"><div><h3 style="margin:0">🥚 Нормативи корму</h3><div class="muted">Вирощування 1–140 · Кладка 140+</div></div><button class="secondary right" onclick="layerNormForm43()">⚙ Налаштувати</button></div>';c.prepend(d)},30)};
const oldOpen43=window.openBatch;window.openBatch=function(id){if(typeof oldOpen43==='function')oldOpen43(id);setTimeout(()=>{const b=batch(id);if(!b||b.kind!=='layer')return;const d=Math.max(1,age(b)),p=lp43(d),r=norm43(d),daily=r?n43(r.recommended_feed_g_head)*heads(b)/1000:0,actual=layerActual43(id,D()),period=layerNormTotal43(b,b.placed_at,D());const box=document.createElement('div');box.className='card section';box.dataset.layerfeed43='1';box.innerHTML=`<h3>🌾 Корм за нормативом</h3><div class="grid g4"><div><span class="muted">Фаза</span><br><b>${e43(p.name)}</b></div><div><span class="muted">Норма</span><br><b>${r?n43(r.recommended_feed_g_head).toFixed(1):'0.0'} г/гол/день</b></div><div><span class="muted">На сьогодні</span><br><b>${daily.toFixed(2)} кг</b></div><div><span class="muted">За період</span><br><b>${period.toFixed(2)} кг</b></div></div><p class="muted">Фактично записано сьогодні: <b>${actual.toFixed(2)} кг</b> · відхилення: <b>${(actual-daily).toFixed(2)} кг</b>. Якщо норматив не заданий, розрахунок дорівнює 0.</p>`;const body=document.querySelector('#tabBody');if(body&&!body.querySelector('[data-layerfeed43]'))body.parentElement?.insertBefore(box,body)},120)};
})();