(()=>{'use strict';
/* FERMA PRO v65: shared client account + numbered orders + active/archive admin view. */
const esc65=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const num65=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const money65=v=>num65(v).toLocaleString('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2})+' грн';
function status65(s){return ({new:'Нове',confirmed:'Підтверджено',processing:'В обробці',ready:'Готово',completed:'Виконано',cancelled:'Скасовано'})[s]||s||'Невідомо'}
async function renderOrder65(o){const ir=await db.from('shop_order_items').select('*').eq('order_id',o.id).order('product_name');const items=ir.data||[];return `<article class="card order section"><div class="row"><b>Замовлення ${esc65(o.order_number||o.id.slice(0,8))}</b><span class="pill">${status65(o.status)}</span><span class="right"><b>${money65(o.total_amount)}</b></span></div><div class="muted">${new Date(o.created_at).toLocaleString('uk-UA')}</div><div style="margin-top:8px"><b>${esc65(o.customer_name)}</b><br>📞 ${esc65(o.phone)}${o.delivery_address?`<br>📍 ${esc65(o.delivery_address)}`:''}</div>${items.map(x=>`<div class="row" style="margin-top:7px"><span>${esc65(x.product_name)}</span><span>${num65(x.quantity)} ${esc65(x.unit)} × ${money65(x.unit_price)}</span><span class="right"><b>${money65(x.line_total)}</b></span></div>`).join('')}${o.comment?`<div class="muted" style="margin-top:8px">💬 ${esc65(o.comment)}</div>`:''}<div class="row" style="margin-top:10px"><select onchange="shopStatus65('${o.id}',this.value)">${['new','confirmed','processing','ready','completed','cancelled'].map(s=>`<option value="${s}" ${s===o.status?'selected':''}>${status65(s)}</option>`).join('')}</select><button class="secondary small" onclick="shopOrder65('${o.id}')">Деталі</button></div></article>`}
window.shopAdmin61=async function(){const [pr,or]=await Promise.all([db.from('shop_products').select('*').order('sort_order').order('name'),db.from('shop_orders').select('*').order('created_at',{ascending:false})]);if(pr.error)return alert(pr.error.message);if(or.error)return alert(or.error.message);const products=pr.data||[],orders=or.data||[];const active=orders.filter(x=>!['completed','cancelled'].includes(x.status));const archived=orders.filter(x=>['completed','cancelled'].includes(x.status));$('title').textContent='Магазин';document.querySelectorAll('.nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page==='shop'));$('content').innerHTML=`<div class="row"><button class="primary" onclick="shopProductForm61()">＋ Додати товар</button><button class="secondary" onclick="shopAdmin61()">↻ Оновити</button><button class="secondary" onclick="shopWarehouse64()">🏪 Склад магазину</button><button class="secondary" onclick="shopReport64()">📊 Звіт магазину</button><span class="pill">Товарів: ${products.length}</span><span class="pill">Нових/активних: ${active.length}</span></div><div class="section card"><h3>🛒 Товари магазину</h3><table class="table"><thead><tr><th>Товар</th><th>Ціна</th><th>Наявність</th><th>Статус</th><th></th></tr></thead><tbody>${products.map(p=>`<tr><td><b>${esc65(p.name)}</b><br><span class="muted">${esc65(p.category||'')} · ${esc65(p.unit)}</span></td><td>${money65(p.price)}</td><td>${num65(p.stock_qty)} ${esc65(p.unit)}</td><td>${p.is_active?'Активний':'Прихований'}</td><td><button class="secondary small" onclick="shopProductForm61('${p.id}')">Редагувати</button> <button class="danger small" onclick="shopToggle61('${p.id}',${!p.is_active})">${p.is_active?'Приховати':'Показати'}</button></td></tr>`).join('')||'<tr><td colspan="5">Товарів немає.</td></tr>'}</tbody></table></div><div class="section"><div class="row"><h3 style="margin:0">📦 Нові та активні замовлення</h3><span class="pill">${active.length}</span></div>${active.length? (await Promise.all(active.map(renderOrder65))).join(''):'<div class="card muted">Нових замовлень немає.</div>'}</div><details class="section card"><summary><b>🗄️ Архів замовлень</b> <span class="pill">${archived.length}</span></summary><div style="margin-top:12px">${archived.length?(await Promise.all(archived.map(renderOrder65))).join(''):'<div class="muted">Архів порожній.</div>'}</div></details>`}
window.shopStatus65=async function(id,status){const r=await db.from('shop_orders').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return alert(r.error.message);shopAdmin61()};
window.shopOrder65=async function(id){const [o,i]=await Promise.all([db.from('shop_orders').select('*').eq('id',id).single(),db.from('shop_order_items').select('*').eq('order_id',id).order('product_name')]);if(o.error)return alert(o.error.message);const x=o.data;openModal(`<h3>Замовлення ${esc65(x.order_number||x.id.slice(0,8))}</h3><p><b>${esc65(x.customer_name)}</b><br>📞 ${esc65(x.phone)}${x.delivery_address?`<br>📍 ${esc65(x.delivery_address)}`:''}</p>${(i.data||[]).map(a=>`<div class="card" style="margin:7px 0"><div class="row"><b>${esc65(a.product_name)}</b><span class="right">${money65(a.line_total)}</span></div><span class="muted">${num65(a.quantity)} ${esc65(a.unit)} × ${money65(a.unit_price)}</span></div>`).join('')}<h3>Разом: ${money65(x.total_amount)}</h3>${x.comment?`<p class="muted">${esc65(x.comment)}</p>`:''}<button class="secondary" onclick="closeModal()">Закрити</button>`)};
})();