(()=>{'use strict';
/* FERMA PRO v46: livestock event schema compatibility.
   The DB livestock_events table has total_amount, not total_preview.
   Normalize culling/sale payloads before write and keep stock/accounting synchronized.
*/
const n46=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
function cleanEvent46(p){const x={...(p||{})};delete x.total_preview;if(x.total_amount===undefined&&x.total_preview!==undefined)x.total_amount=n46(x.total_preview);if(x.heads!==undefined)x.heads=Math.max(0,Math.round(n46(x.heads)));if(x.weight_kg!==undefined)x.weight_kg=n46(x.weight_kg);if(x.price_per_kg!==undefined)x.price_per_kg=n46(x.price_per_kg);if(x.total_amount!==undefined)x.total_amount=n46(x.total_amount);return x}
window.saveLivestockEvent46=async function(payload,id){if(!window.user||!window.db)throw new Error('Сесія користувача не готова');const p=cleanEvent46(payload);if(!p.event_type)throw new Error('Не вказано тип операції');if(!p.batch_id)throw new Error('Не вказано партію');if(!p.event_date)p.event_date=typeof D==='function'?D():new Date().toISOString().slice(0,10);const q=id?await db.from('livestock_events').update(p).eq('id',id).eq('user_id',user.id).select('*').single():await db.from('livestock_events').insert({...p,user_id:user.id}).select('*').single();if(q.error)throw q.error;if(typeof load==='function')await load();return q.data};
function patchCullingForm46(){const root=document.querySelector('#modalBody');if(!root)return;const txt=(root.innerText||'').toLowerCase();if(!/вибраку|вибракуван|cull|вилуч/.test(txt))return;root.querySelectorAll('input[name="total_preview"],input[id="total_preview"],input[data-field="total_preview"]').forEach(x=>{x.name='total_amount';x.id='total_amount';x.dataset.field='total_amount'});const forms=root.querySelectorAll('form');forms.forEach(f=>{if(f.dataset.v46)return;const old=f.onsubmit;if(typeof old!=='function')return;f.dataset.v46='1';f.onsubmit=async function(ev){ev.preventDefault();try{const fd=new FormData(f),p={};fd.forEach((v,k)=>{if(k!=='total_preview')p[k]=v});if(fd.has('total_preview')&&!fd.has('total_amount'))p.total_amount=fd.get('total_preview');await window.saveLivestockEvent46(p);if(typeof closeModal==='function')closeModal();else f.closest('.modal')?.classList.add('hidden');alert('Операцію збережено.')}catch(e){console.error('FERMA v46 culling',e);alert('Помилка при вибракуванні бройлера: '+(e?.message||e))}}})}
const mo46=new MutationObserver(patchCullingForm46);if(document.body)mo46.observe(document.body,{childList:true,subtree:true});setTimeout(patchCullingForm46,500);
})();