(()=>{'use strict';
/* FERMA PRO v59: recipe editor with selectable feed phase and warehouse prices. */
const N59=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const E59=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const F59=v=>N59(v).toLocaleString('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2});
const norm59=v=>String(v??'').trim().toLowerCase().replace(/\s+/g,' ');
async function items59(){try{const r=await db.from('warehouse_items').select('id,name,price_per_unit,unit,item_type').order('name');if(!r.error&&Array.isArray(r.data))return r.data}catch(e){console.error('v59 warehouse',e)}return Array.isArray(C.items)?C.items:[]}
async function phases59(){const src=Array.isArray(C.phases)?C.phases:[];if(src.length)return src;for(const t of ['feed_phases','phases']){try{const r=await db.from(t).select('*');if(!r.error&&Array.isArray(r.data)&&r.data.length)return r.data}catch(e){}}return []}
async function item59(id,name){try{if(id){const r=await db.from('warehouse_items').select('id,name,price_per_unit,unit,item_type').eq('id',id).maybeSingle();if(!r.error&&r.data)return r.data}if(name){const r=await db.from('warehouse_items').select('id,name,price_per_unit,unit,item_type').ilike('name',String(name).trim()).limit(1);if(!r.error&&r.data?.[0])return r.data[0]}}catch(e){console.error('v59 price',e)}return null}
function phaseName59(p){return String(p?.name||p?.phase||p?.title||((p?.from_day!=null||p?.to_day!=null)?`День ${p.from_day??''}-${p.to_day??''}`:'')).trim()}
function phaseOptions59(phases,current){let a=phases.map(phaseName59).filter(Boolean);if(current&&!a.some(x=>norm59(x)===norm59(current)))a.unshift(current);return [...new Set(a)].map(x=>`<option value="${E59(x)}" ${norm59(x)===norm59(current)?'selected':''}>${E59(x)}</option>`).join('')}
function line59(items,x={}){const found=items.find(a=>String(a.id)===String(x.item_id))||items.find(a=>norm59(a.name)===norm59(x.ingredient_name));return `<div class="r59-line card" style="margin:8px 0;padding:10px"><div class="grid g3"><div class="field"><label>Інгредієнт зі складу</label><select class="r59-item" required><option value="">Оберіть інгредієнт</option>${items.map(a=>`<option value="${E59(a.id)}" ${found&&String(a.id)===String(found.id)?'selected':''}>${E59(a.name)}</option>`).join('')}</select><small class="muted r59-info">Ціна підтягується зі складу</small></div><div class="field"><label>Кількість, кг</label><input class="r59-kg" type="number" min=".001" step=".001" required value="${x.kg?N59(x.kg):''}"></div><div class="field"><label>Ціна, грн/кг</label><input class="r59-price" type="number" readonly value="${N59(x.price_per_kg)>0?N59(x.price_per_kg):''}" style="background:#f3f4f6;font-weight:700"><small class="muted r59-label">${N59(x.price_per_kg)>0?F59(x.price_per_kg)+' грн/кг':'Виберіть інгредієнт'}</small></div></div><div class="row"><span class="pill r59-cost">Вартість: 0.00 грн</span><button type="button" class="danger small r59-del">× Видалити</button></div></div>`}
function calc59(f){let kg=0,c=0;f?.querySelectorAll('.r59-line').forEach(r=>{const q=N59(r.querySelector('.r59-kg')?.value),p=N59(r.querySelector('.r59-price')?.value);kg+=q;c+=q*p;r.querySelector('.r59-cost').textContent='Вартість: '+F59(q*p)+' грн'});const s=f?.querySelector('.r59-total');if(s)s.textContent='Разом: '+kg.toFixed(3)+' кг • '+(kg?F59(c/kg):'0.00')+' грн/кг • '+F59(c)+' грн'}
async function sync59(r,f){const s=r.querySelector('.r59-item'),p=r.querySelector('.r59-price'),lab=r.querySelector('.r59-label'),info=r.querySelector('.r59-info');if(!s||!p)return;const name=s.options[s.selectedIndex]?.text||'';if(!s.value){p.value='';lab.textContent='Виберіть інгредієнт';calc59(f);return}const d=await item59(s.value,name),v=N59(d?.price_per_unit);p.value=v>0?String(v):'';lab.textContent=v>0?F59(v)+' грн/кг':'Ціна не задана на складі';info.textContent=d?'Склад: '+d.name+' • Ціна: '+F59(v)+' грн':'Не знайдено на складі';calc59(f)}
async function form59(id){const [items,phases]=await Promise.all([items59(),phases59()]);const r=id&&Array.isArray(C.recipes)?C.recipes.find(x=>String(x.id)===String(id)):null;const lines=id&&Array.isArray(C.lines)?C.lines.filter(x=>String(x.recipe_id)===String(id)):[];openModal(`<h3>${r?'Редагувати':'Новий'} рецепт</h3><form id="r59form"><div class="grid g2"><div class="field"><label>Назва рецепту</label><input name="name" required value="${E59(r?.name||'')}"></div><div class="field"><label>Фаза корму</label><select name="phase" required><option value="">Оберіть фазу корму</option>${phaseOptions59(phases,r?.phase||'')}</select>${!phases.length?'<small class="muted">Фази ще не налаштовані. Додайте їх у налаштуваннях корму.</small>':''}</div></div><div id="r59lines" class="section">${(lines.length?lines:[{}]).map(x=>line59(items,x)).join('')}</div><div class="row"><button type="button" class="secondary" id="r59add">＋ Інгредієнт</button><span class="pill r59-total">Разом: 0.000 кг • 0.00 грн/кг • 0.00 грн</span></div><p class="muted">🔒 Ціна інгредієнта береться тільки зі сторінки <b>Склад</b>.</p><div class="row"><button type="button" class="secondary" onclick="closeModal()">Скасувати</button><button class="primary">Зберегти рецепт</button></div></form>`);const f=$('r59form');if(!f)return;const bind=rw=>{rw.querySelector('.r59-item').onchange=()=>sync59(rw,f);rw.querySelector('.r59-kg').oninput=()=>calc59(f);rw.querySelector('.r59-del').onclick=()=>{rw.remove();calc59(f)};sync59(rw,f)};f.querySelectorAll('.r59-line').forEach(bind);$('r59add').onclick=()=>{$('r59lines').insertAdjacentHTML('beforeend',line59(items,{}));bind($('r59lines').lastElementChild)};f.onsubmit=async e=>{e.preventDefault();const name=f.elements.name.value.trim(),phase=f.elements.phase.value;if(!name)return alert('Вкажіть назву рецепту');if(!phase)return alert('Оберіть фазу корму');const out=[];for(const rw of f.querySelectorAll('.r59-line')){const s=rw.querySelector('.r59-item'),q=N59(rw.querySelector('.r59-kg').value),nm=s.options[s.selectedIndex]?.text||'';if(!s.value||q<=0)continue;const d=await item59(s.value,nm),p=N59(d?.price_per_unit);if(!d||p<=0)return alert('Для «'+nm+'» не задана ціна на складі.');out.push({item_id:d.id,ingredient_name:d.name,kg:q,price_per_kg:p})}if(!out.length)return alert('Додайте інгредієнти з кількістю');let z,rr;if(id){z=await db.from('feed_recipes').update({name,phase}).eq('id',id).eq('user_id',user.id).select().single();if(z.error)return alert(z.error.message);rr=z.data}else{z=await db.from('feed_recipes').insert({name,phase,user_id:user.id}).select().single();if(z.error)return alert(z.error.message);rr=z.data}z=await db.from('feed_recipe_lines').delete().eq('recipe_id',rr.id).eq('user_id',user.id);if(z.error)return alert(z.error.message);z=await db.from('feed_recipe_lines').insert(out.map(a=>({...a,recipe_id:rr.id,user_id:user.id})));if(z.error)return alert(z.error.message);await load();closeModal()};calc59(f)}
window.recipeForm=form59;window.openRecipeWarehouse59=form59;
document.addEventListener('click',e=>{const b=e.target.closest?.('[onclick]');if(!b)return;const oc=b.getAttribute('onclick')||'';const m=oc.match(/recipeForm\s*\(\s*(?:['"]([^'"]*)['"])?\s*\)/);if(!m)return;e.preventDefault();e.stopImmediatePropagation();form59(m[1]||null)},true);
setInterval(()=>{if(window.recipeForm!==form59)window.recipeForm=form59},300);
})();