(()=>{'use strict';
/* FERMA PRO v44: layer report with normative feed, actual feed, eggs, revenue, expenses and cost metrics. */
const n44=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const esc44=v=>typeof E==='function'?E(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date44=v=>String(v||'').slice(0,10);
const in44=(d,f,t)=>{d=date44(d);return(!f||d>=f)&&(!t||d<=t)};
const heads44=b=>typeof heads==='function'?n44(heads(b)):n44(b?.current_heads??b?.initial_heads);
const age44=b=>typeof age==='function'?Math.max(1,n44(age(b))):1;
const phase44=d=>d<140?'Вирощування':'Кладка';
function norm44(b,d){const rows=(C.phases||[]).filter(x=>x.kind==='layer');const p=phase44(d);const r=rows.find(x=>x.name===p&&Number(x.from_day)=== (p==='Вирощування'?1:140));return n44(r?.recommended_feed_g_head)}
function totalNorm44(b,f,t){const placed=date44(b?.placed_at),from=f&&f>placed?f:placed,to=t||D();const a=new Date(from+'T00:00:00'),z=new Date(to+'T00:00:00');if(z<a)return 0;let total=0;for(let x=new Date(a);x<=z;x.setDate(x.getDate()+1)){const d=Math.max(1,Math.floor((x-new Date(placed+'T00:00:00'))/86400000)+1);total+=norm44(b,d)*heads44(b)/1000}return total}
function actual44(bid,f,t){return(C.daily||[]).filter(x=>x.batch_id===bid&&in44(x.record_date,f,t)).reduce((s,x)=>s+n44(x.feed_kg),0)}
function eggs44(bid,f,t){return(C.eggSales||[]).filter(x=>x.batch_id===bid&&in44(x.sale_date,f,t)).reduce((s,x)=>s+n44(x.quantity??x.eggs_count??x.qty),0)}
function eggIncome44(bid,f,t){return(C.eggSales||[]).filter(x=>x.batch_id===bid&&in44(x.sale_date,f,t)).reduce((s,x)=>s+n44(x.total_amount),0)}
function fin44(bid,f,t){return(C.fin||[]).filter(x=>(!x.batch_id||x.batch_id===bid)&&in44(x.operation_date,f,t)&&x.operation_type==='expense').reduce((s,x)=>s+n44(x.amount),0)}
function birdIncome44(bid,f,t){return(C.events||[]).filter(x=>x.batch_id===bid&&x.event_type==='sale'&&in44(x.event_date,f,t)).reduce((s,x)=>s+n44(x.total_amount),0)}
function layerReport44(){const c=document.querySelector('#content');if(!c)return;const from=document.querySelector('#r39from')?.value||new Date().getFullYear()+'-01-01',to=document.querySelector('#r39to')?.value||D(),sel=document.querySelector('#r39batch')?.value||'';const bs=(C.batches||[]).filter(b=>b.kind==='layer'&&(!sel||String(b.id)===String(sel)));if(!bs.length)return;
 let rows='',tot={heads:0,norm:0,act:0,eggs:0,eggInc:0,birdInc:0,exp:0};
 for(const b of bs){const h=heads44(b),d=age44(b),normDay=norm44(b,d),norm=totalNorm44(b,from,to),act=actual44(b.id,from,to),eg=eggs44(b.id,from,to),ei=eggIncome44(b.id,from,to),bi=birdIncome44(b.id,from,to),ex=fin44(b.id,from,to),cost=ex+bi*0+ n44(b.initial_heads)*n44(b.chick_price);tot.heads+=h;tot.norm+=norm;tot.act+=act;tot.eggs+=eg;tot.eggInc+=ei;tot.birdInc+=bi;tot.exp+=ex;rows+=`<tr><td>${esc44(b.name)}</td><td>${h}</td><td>${esc44(phase44(d))}</td><td>${normDay.toFixed(1)}</td><td>${norm.toFixed(2)}</td><td>${act.toFixed(2)}</td><td>${(act-norm).toFixed(2)}</td><td>${eg}</td><td>${ei.toFixed(2)} грн</td><td>${ex.toFixed(2)} грн</td><td>${cost.toFixed(2)} грн</td></tr>`}
 const net=tot.eggInc+tot.birdInc-tot.exp;const costKg=tot.act?tot.exp/tot.act:0;const eggCost=tot.eggs?tot.exp/tot.eggs:0;
 const old=c.querySelector('[data-layerreport44]');if(old)old.remove();const box=document.createElement('div');box.dataset.layerreport44='1';box.className='card section';box.innerHTML=`<div class="row"><div><h2 style="margin:0">🥚 Звіт по несучках</h2><div class="muted">Період: ${esc44(from)} — ${esc44(to)} · фази: Вирощування 1–140 / Кладка 140+</div></div><button class="secondary noPrint" onclick="window.print()">🖨 Друк</button></div><div class="grid g4" style="margin-top:12px"><div class="card"><span class="muted">Нормативний корм</span><div class="stat">${tot.norm.toFixed(2)} кг</div></div><div class="card"><span class="muted">Фактичний корм</span><div class="stat">${tot.act.toFixed(2)} кг</div></div><div class="card"><span class="muted">Яйця</span><div class="stat">${tot.eggs}</div></div><div class="card"><span class="muted">Чистий результат*</span><div class="stat">${net.toFixed(2)} грн</div></div></div><div style="overflow:auto;margin-top:12px"><table class="table"><thead><tr><th>Партія</th><th>Гол.</th><th>Фаза</th><th>Норма г/гол/день</th><th>Норма корму кг</th><th>Факт кг</th><th>Відхилення кг</th><th>Яйця</th><th>Продаж яєць</th><th>Витрати</th><th>Вартість молодняку</th></tr></thead><tbody>${rows}</tbody><tfoot><tr><th>Разом</th><th>${tot.heads}</th><th>—</th><th>—</th><th>${tot.norm.toFixed(2)}</th><th>${tot.act.toFixed(2)}</th><th>${(tot.act-tot.norm).toFixed(2)}</th><th>${tot.eggs}</th><th>${tot.eggInc.toFixed(2)} грн</th><th>${tot.exp.toFixed(2)} грн</th><th>—</th></tr></tfoot></table></div><p class="muted" style="margin-bottom:0">Корм на яйце: <b>${eggCost.toFixed(3)} грн/яйце</b> за витратами, що внесені у фінансовий облік. *Чистий результат тут: продаж яєць + продаж птиці − фінансові витрати, без автоматичного розподілу корму/молодняку в собівартість.</p>`;c.appendChild(box)}
window.layerReport44=layerReport44;
function watch44(){const c=document.querySelector('#content');if(!c)return;if(/звіт|report/i.test(c.innerText||'')){setTimeout(layerReport44,40)}}
const oldReports44=window.reports; if(typeof oldReports44==='function'){window.reports=function(){oldReports44();setTimeout(layerReport44,80)}}
const mo44=new MutationObserver(()=>watch44());if(document.body)mo44.observe(document.body,{childList:true,subtree:true});setTimeout(watch44,500);
/* Canonicalize newly saved layer recipes after v39/v43 handlers run. */
const rf44=window.recipeForm;if(typeof rf44==='function'){window.recipeForm=async function(id){return rf44(id)}}
})();