(()=>{'use strict';
/* FERMA PRO v53: definitive recipe form. Intercepts the old inline recipeForm button and uses warehouse_items.price_per_unit as the only ingredient price source. */
const N53=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const E53=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const items53=()=>Array.isArray(C.items)?C.items.filter(i=>i&&i.id):[];
const local53=id=>items53().find(i=>String(i.id)===String(id));
const wh53=async id=>{try{const r=await db.from('warehouse_items').select('id,name,price_per_unit,unit,item_type').eq('id',id).maybeSingle();if(r.error)throw r.error;return r.data||local53(id)||null}catch(e){console.error('FERMA v53 warehouse price',e);return local53(id)||null}};
const priceText53=p=>p>0?N53(p).toLocaleString('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2})+' грн/кг':'Ціну не задано на складі';
function ingredientOptions53(selected){return items53().map(i=>`<option value="${E53(i.id)}" ${String(i.id)===String(selected)?'selected':''}>${E53(i.name)}</option>`).join('')}
function row53(x={}){const id=x.item_id||'';const p=N53(x.price_per_kg);return `<div class="recipe53-line card" style="margin:8px 0;padding:10px" data-item-id="${E53(id)}"><div class="grid g3"><div class="field"><label>Інгредієнт зі складу</label><select class="r53-item" name="item_id" required><option value="">Оберіть інгредієнт</option>${ingredientOptions53(id)}</select><small class="muted r53-stock">Ціна береться автоматично зі складу</small></div><div class="field"><label>Кількість, кг</label><input class="r53-kg" name="kg" type="number" min=".001" step=".001" required value="${x.kg?N53(x.kg):''}"></div><div class="field"><label>Ціна зі складу, грн/кг</label><input class="r53-price" name="price_per_kg" type="number" readonly value="${p>0?p:''}" style="background:#f3f4f6;font-weight:700"><small class="muted r53-price-label">${p>0?priceText53(p):'Оберіть інгредієнт'}</small></div></div><div class="row"><span class="pill r53-cost">Вартість: 0.00 грн</span><button type="button" class="danger small r53-remove">× Видалити</button></div></div>`}
async function sync53(line){const s=line.querySelector('.r53-item'),price=line.querySelector('.r53-price'),label=line.querySelector('.r53-price-label'),stock=line.querySelector('.r53-stock');if(!s||!price)return;const d=await wh53(s.value);const p=N53(d?.price_per_unit);price.value=p>0?String(p):'';label.textContent=p>0?priceText53(p):'Ціну не задано на складі';stock.textContent=d?`Склад: ${E53(d.name)} • актуальна ціна`:'Інгредієнт не знайдено на складі';line.dataset.itemId=s.value;calc53(line.closest('form'))}
function calc53(form){if(!form)return;let totalKg=0,total=0;form.querySelectorAll('.recipe53-line').forEach(line=>{const kg=N53(line.querySelector('.r53-kg')?.value),p=N53(line.querySelector('.r53-price')?.value),c=kg*p;totalKg+=kg;total+=c;const out=line.querySelector('.r53-cost');if(out)out.textContent=`Вартість: ${c.toLocaleString('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2})} грн`});const s=form.querySelector('.r53-summary');if(s)s.innerHTML=`Разом: <b>${totalKg.toFixed(3)} кг</b> • <b>${totalKg?(total/totalKg).toLocaleString('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2}):'0.00'} грн/кг</b> • <b>${total.toLocaleString('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2})} грн</b>`}
async function open53(id){const r=id?C.recipes.find(x=>String(x.id)===String(id)):null;const lines=id?C.lines.filter(x=>String(x.recipe_id)===String(id)):[{}];openModal(`<h3>${r?'Редагувати':'Новий'} рецепт</h3><form id="recipeForm53"><div class="grid g2"><div class="field"><label>Назва рецепту</label><input name="name" required value="${E53(r?.name||'')}"></div><div class="field"><label>Фаза</label><input name="phase" value="${E53(r?.phase||'')}"></div></div><div id="recipeLines53" class="section">${(lines.length?lines:[{}]).map(row53).join('')}</div><div class="row"><button type="button" class="secondary" id="addR53">＋ Інгредієнт</button><span class="pill r53-summary">Разом: <b>0.000 кг</b> • <b>0.00 грн/кг</b> • <b>0.00 грн</b></span></div><p class="muted">🔒 Ціна інгредієнта не вводиться вручну. Вона щоразу береться з <b>Складу → Ціна за од.</b></p><div class="row"><button type="button" class="secondary" onclick="closeModal()">Скасувати</button><button class="primary">Зберегти рецепт</button></div></form>`);
const f=$('recipeForm53');if(!f)return;
f.querySelectorAll('.recipe53-line').forEach(line=>sync53(line));
$('addR53').onclick=()=>{const box=$('recipeLines53');box.insertAdjacentHTML('beforeend',row53({}));const line=box.lastElementChild;bind53(line);calc53(f)};
f.onsubmit=async e=>{e.preventDefault();const name=f.elements.name.value.trim();if(!name)return alert('Вкажіть назву рецепту');const lineEls=[...f.querySelectorAll('.recipe53-line')];if(!lineEls.length)return alert('Додайте хоча б один інгредієнт');const rows=[];for(const line of lineEls){const itemId=line.querySelector('.r53-item')?.value;const kg=N53(line.querySelector('.r53-kg')?.value);if(!itemId||kg<=0)continue;const d=await wh53(itemId);const p=N53(d?.price_per_unit);if(p<=0)return alert(`Для «${d?.name||'інгредієнта'}» на складі не задана ціна.`);rows.push({item_id:itemId,ingredient_name:d.name,kg,price_per_kg:p});}if(!rows.length)return alert('Додайте інгредієнти з кількістю');let rr;if(id){const u=await db.from('feed_recipes').update({name,phase:f.elements.phase.value.trim()}).eq('id',id).eq('user_id',user.id).select().single();if(u.error)return alert(u.error.message);rr=u.data}else{const ins=await db.from('feed_recipes').insert({name,phase:f.elements.phase.value.trim(),user_id:user.id}).select().single();if(ins.error)return alert(ins.error.message);rr=ins.data}const dl=await db.from('feed_recipe_lines').delete().eq('recipe_id',rr.id).eq('user_id',user.id);if(dl.error)return alert(dl.error.message);const insLines=await db.from('feed_recipe_lines').insert(rows.map(x=>({...x,recipe_id:rr.id,user_id:user.id})));if(insLines.error)return alert(insLines.error.message);await load();closeModal()};calc53(f)}
function bind53(line){const s=line.querySelector('.r53-item'),kg=line.querySelector('.r53-kg'),rm=line.querySelector('.r53-remove');if(s)s.addEventListener('change',()=>sync53(line));if(kg)kg.addEventListener('input',()=>calc53(line.closest('form')));if(rm)rm.onclick=()=>{line.remove();calc53($('recipeForm53'))};}
function intercept53(e){const b=e.target.closest?.('button,a');if(!b)return;const oc=b.getAttribute('onclick')||'';if(!/recipeForm\s*\(/.test(oc))return;let m=oc.match(/recipeForm\s*\(\s*['"]([^'"]+)['"]\s*\)/);const id=m?m[1]:null;e.preventDefault();e.stopImmediatePropagation();open53(id)}
document.addEventListener('click',intercept53,true);
window.openRecipeWarehouse53=open53;
})();