(()=>{'use strict';
/* FERMA PRO: FCR, biomass, sales and adjustment hardening */
const n9=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const dec9=new Set(['mortality','sale','home','cull']);
window.gainKg=function(id){const b=batch(id),w=weights(id);if(!b||!w.length)return 0;const latest=w[w.length-1],start=n9(b.start_weight_g)||n9(w[0]?.average_weight_g);const live=heads(b);if(start<=0||live<=0||n9(latest.average_weight_g)<=0)return 0;return Math.max(0,live*n9(latest.average_weight_g)/1000-n9(b.initial_heads)*start/1000)};
window.soldWeightKg=function(id){return C.events.filter(x=>x.batch_id===id&&x.event_type==='sale').reduce((s,x)=>s+n9(x.weight_kg),0)};
window.producedGainKg=function(id){const b=batch(id),w=weights(id);if(!b||!w.length)return 0;const latest=w[w.length-1],start=n9(b.start_weight_g)||n9(w[0]?.average_weight_g);const currentBiomass=heads(b)*n9(latest.average_weight_g)/1000;const sold=soldWeightKg(id);const initial=n9(b.initial_heads)*start/1000;return Math.max(0,currentBiomass+sold-initial)};
window.fcr=function(id){const g=producedGainKg(id);const f=n9(feedKg(id));return g>0?f/g:0};
window.totalBirdWeightKg=function(id){const b=batch(id),w=latestWeight(id);return b&&w?n9(heads(b))*n9(w.average_weight_g)/1000:0};
window.eventForm=function(bid,id){const x=id?C.events.find(e=>e.id===id):null;const types=[['mortality','Падіж'],['sale','Продаж'],['home','Додому'],['cull','Вибракування'],['adjustment','Коригування']];openModal(`<h3>${x?'Редагування':'Додати'} рух птиці</h3><form id="form" class="grid g2"><div class="field"><label>Дата</label><input name="event_date" type="date" value="${x?.event_date||D()}" required></div><div class="field"><label>Тип</label><select name="event_type" id="eventType" required>${types.map(t=>`<option value="${t[0]}" ${x?.event_type===t[0]?'selected':''}>${t[1]}</option>`).join('')}</select></div><div class="field"><label>Кількість голів</label><input name="heads" id="eventHeads" type="number" step="1" value="${x?x.event_type==='adjustment'?n9(x.heads):Math.abs(n9(x.heads)):''}" required></div><div class="field"><label>Загальна маса, кг</label><input name="weight_kg" type="number" min="0" step=".001" value="${n9(x?.weight_kg)||''}"></div><div class="field"><label>Ціна за кг, грн</label><input name="price_per_kg" type="number" min="0" step=".01" value="${n9(x?.price_per_kg)||''}"></div><div class="field"><label>Клієнт</label><input name="client" value="${E(x?.client||'')}"></div><div class="field" style="grid-column:1/-1"><label>Примітка</label><input name="notes" value="${E(x?.notes||'')}"></div><button class="primary">Зберегти</button></form>`);const sync=()=>{const adj=$('eventType').value==='adjustment';$('eventHeads').min=adj?'':0;$('eventHeads').placeholder=adj?'Напр. -2 або +2':''};sync();$('eventType').onchange=sync;$('form').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));p.batch_id=bid;p.heads=n9(p.heads);p.weight_kg=n9(p.weight_kg);p.price_per_kg=n9(p.price_per_kg);if(p.event_type!=='adjustment'&&p.heads<0)p.heads=Math.abs(p.heads);p.total_amount=p.event_type==='sale'?p.weight_kg*p.price_per_kg:0;const b=batch(bid);let available=heads(b)+(x&&dec9.has(x.event_type)?n9(x.heads):0);if(dec9.has(p.event_type)&&p.heads>available)return alert(`Недостатньо птиці. Доступно: ${available} гол.`);if(p.event_type==='sale'&&p.weight_kg<=0)return alert('Для продажу вкажіть загальну масу.');if(await save('livestock_events',p,id)){closeModal();openBatch(bid)}}};
})();
