(()=>{'use strict';
/* FERMA PRO: transactional edit safety for feed and medicine warehouse links */
const n25=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const auto25=(prefix,id)=>C.moves.filter(m=>m.user_id===user.id&&String(m.notes||'')===`${prefix}:${id}`);
async function restore25(m){const p={user_id:user.id,item_id:m.item_id,batch_id:m.batch_id||null,movement_type:m.movement_type,movement_date:m.movement_date,quantity:n25(m.quantity),unit_price:n25(m.unit_price),total_amount:n25(m.total_amount),adjustment_direction:m.adjustment_direction||null,reference_id:m.reference_id||null,supplier:m.supplier||null,notes:m.notes||null};const r=await db.from('warehouse_movements').insert(p);return !r.error}
async function replaceAuto25(prefix,id,newItemId,newQty,date,unitPrice,batchId){
 const oldMoves=auto25(prefix,id),old=oldMoves[0]||null;
 if(newItemId&&newQty>0){const stock=C.moves.filter(m=>m.item_id===newItemId&&m.id!==(old?.id||'')).reduce((s,m)=>s+(m.movement_type==='in'||(m.movement_type==='adjustment'&&m.adjustment_direction==='in')?n25(m.quantity):-n25(m.quantity)),0);if(newQty>stock)throw new Error(`Недостатньо залишку на складі. Доступно: ${stock.toFixed(3)}`)}
 for(const m of oldMoves){const r=await db.from('warehouse_movements').delete().eq('id',m.id).eq('user_id',user.id);if(r.error){for(const gone of oldMoves.slice(0,oldMoves.indexOf(m)))await restore25(gone);throw new Error('Не вдалося видалити старе складське списання: '+r.error.message)}}
 if(newItemId&&newQty>0){const r=await db.from('warehouse_movements').insert({user_id:user.id,item_id:newItemId,batch_id:batchId,movement_type:'use',movement_date:date,quantity:newQty,unit_price:unitPrice,total_amount:newQty*unitPrice,reference_id:id,notes:`${prefix}:${id}`});if(r.error){if(old)await restore25(old);throw new Error('Не вдалося створити нове складське списання. Старе відновлено: '+r.error.message)}}
}
const oldDaily25=window.dailyForm;
window.dailyForm=function(bid,id){oldDaily25(bid,id);const form=$('form');if(!form)return;form.onsubmit=async e=>{e.preventDefault();const f=e.target,x=id?C.daily.find(d=>d.id===id):null,p=Object.fromEntries(new FormData(f));p.batch_id=bid;p.feed_item_id=f.feed_item_id.value||null;['feed_kg','water_l','water_cost','medicine_cost','bedding_cost','electricity_cost','labor_cost','other_cost'].forEach(k=>p[k]=n25(p[k]));try{if(id){const oldMoves=auto25('AUTO_FEED',id);const oldSnapshot=oldMoves.map(m=>({...m}));const oldRow={...x};const r=await db.from('daily_records').update(p).eq('id',id).eq('user_id',user.id);if(r.error)throw new Error('Не вдалося оновити денний запис: '+r.error.message);try{await replaceAuto25('AUTO_FEED',id,p.feed_item_id,n25(p.feed_kg),p.record_date,n25(C.items.find(i=>i.id===p.feed_item_id)?.price_per_unit),bid)}catch(err){await db.from('daily_records').update(oldRow).eq('id',id).eq('user_id',user.id);throw err}}
else{const r=await db.from('daily_records').insert({...p,user_id:user.id}).select().single();if(r.error)throw new Error(r.error.message);try{await replaceAuto25('AUTO_FEED',r.data.id,p.feed_item_id,n25(p.feed_kg),p.record_date,n25(C.items.find(i=>i.id===p.feed_item_id)?.price_per_unit),bid)}catch(err){await db.from('daily_records').delete().eq('id',r.data.id).eq('user_id',user.id);throw err}}
await load();closeModal();openBatch(bid)}catch(err){alert(err.message)}}};
const oldTreat25=window.treatForm;
window.treatForm=function(bid,id){oldTreat25(bid,id);const form=$('form');if(!form)return;form.onsubmit=async e=>{e.preventDefault();const f=e.target,x=id?C.treat.find(t=>t.id===id):null,p=Object.fromEntries(new FormData(f));p.batch_id=bid;p.birds=n25(p.birds);p.used_qty=n25(p.used_qty);p.price_per_unit=n25(p.price_per_10ml)/10;p.total_cost=p.used_qty*p.price_per_unit;p.medicine_item_id=f.medicine_item_id.value||null;delete p.price_per_10ml;try{if(id){const oldMoves=auto25('AUTO_MED',id);const oldRow={...x};const r=await db.from('treatments').update(p).eq('id',id).eq('user_id',user.id);if(r.error)throw new Error('Не вдалося оновити лікування: '+r.error.message);try{await replaceAuto25('AUTO_MED',id,p.medicine_item_id,n25(p.used_qty),p.treatment_date,n25(p.price_per_unit),bid)}catch(err){await db.from('treatments').update(oldRow).eq('id',id).eq('user_id',user.id);throw err}}
else{const r=await db.from('treatments').insert({...p,user_id:user.id}).select().single();if(r.error)throw new Error(r.error.message);try{await replaceAuto25('AUTO_MED',r.data.id,p.medicine_item_id,n25(p.used_qty),p.treatment_date,n25(p.price_per_unit),bid)}catch(err){await db.from('treatments').delete().eq('id',r.data.id).eq('user_id',user.id);throw err}}
await load();closeModal();openBatch(bid)}catch(err){alert(err.message)}}};
})();
