(()=>{'use strict';
/* FERMA PRO v50: unified bird movement ledger, edit-safe balances, schema-safe writes. */
const n50=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const esc50=v=>typeof E==='function'?E(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TYPES50={mortality:'Падіж',sale:'Продаж',home:'Додому',cull:'Вибракування',adjustment:'Коригування'};
const ev50=bid=>(C.events||[]).filter(x=>String(x.batch_id)===String(bid));
function signed50(x){const t=String(x.event_type||'');if(['mortality','sale','home','cull'].includes(t))return-n50(x.heads);if(t==='adjustment'){const s=String(x.notes||'').toLowerCase();return/(^|\s)(in|прихід|додано|додав|плюс)/.test(s)?n50(x.heads):-n50(x.heads)}return 0}
function balance50(bid,ignoreId){const b=(C.batches||[]).find(x=>String(x.id)===String(bid));if(!b)return 0;return Math.max(0,Math.round(n50(b.initial_heads)+ev50(bid).filter(x=>String(x.id)!==String(ignoreId)).reduce((s,x)=>s+signed50(x),0)))}
function clean50(p,bid){const allowed=['batch_id','event_date','event_type','heads','weight_kg','price_per_kg','total_amount','notes','client'];const x={};for(const k of allowed)if(p[k]!==undefined)x[k]=p[k];x.batch_id=bid||x.batch_id;x.event_type=String(x.event_type||'').trim();x.event_date=String(x.event_date||D()).slice(0,10);x.heads=Math.max(1,Math.round(n50(x.heads)));x.weight_kg=Math.max(0,n50(x.weight_kg));x.price_per_kg=Math.max(0,n50(x.price_per_kg));x.total_amount=Math.max(0,n50(x.total_amount));if(x.event_type==='sale'&&x.total_amount<=0)x.total_amount=x.weight_kg*x.price_per_kg;return x}
window.saveMovement50=async function(p,id){if(!user||!db)throw new Error('Сесія користувача не готова');const x=clean50(p,p.batch_id);if(!x.batch_id)throw new Error('Не вказано партію');if(!TYPES50[x.event_type])throw new Error('Невідомий тип операції');const available=balance50(x.batch_id,id);if(x.event_type!=='adjustment'&&x.heads>available)throw new Error(`Недостатньо птиці. Доступно: ${available} гол.`);const q=id?await db.from('livestock_events').update(x).eq('id',id).eq('user_id',user.id).select('*').single():await db.from('livestock_events').insert({...x,user_id:user.id}).select('*').single();if(q.error)throw q.error;await load();return q.data};
window.openMovement50=function(bid,id){const b=(C.batches||[]).find(x=>String(x.id)===String(bid));if(!b)return;const old=id?(C.events||[]).find(e=>String(e.id)===String(id)):null;const available=balance50(bid,id);openModal(`<h3>🐔 ${old?'Редагування руху':'Рух птиці'}: ${esc50(b.name)}</h3><p class="muted">Доступно: <b>${available} гол.</b></p><form id="movement50" class="grid g2"><div class="field"><label>Дата</label><input name="event_date" type="date" value="${esc50(old?.event_date||D())}" required></div><div class="field"><label>Операція</label><select name="event_type"><option value="sale" ${old?.event_type==='sale'?'selected':''}>Продаж</option><option value="mortality" ${old?.event_type==='mortality'?'selected':''}>Падіж</option><option value="cull" ${old?.event_type==='cull'?'selected':''}>Вибракування</option><option value="home" ${old?.event_type==='home'?'selected':''}>Додому</option><option value="adjustment" ${old?.event_type==='adjustment'?'selected':''}>Коригування</option></select></div><div class="field"><label>Кількість, гол.</label><input name="heads" type="number" min="1" step="1" value="${n50(old?.heads)||1}" required></div><div class="field"><label>Маса, кг</label><input name="weight_kg" type="number" min="0" step="0.001" value="${n50(old?.weight_kg)}"></div><div class="field"><label>Ціна, грн/кг</label><input name="price_per_kg" type="number" min="0" step="0.01" value="${n50(old?.price_per_kg)}"></div><div class="field"><label>Сума, грн</label><input name="total_amount" type="number" min="0" step="0.01" value="${n50(old?.total_amount)}"></div><div class="field"><label>Клієнт</label><input name="client" value="${esc50(old?.client||'')}"></div><div class="field"><label>Примітка</label><input name="notes" value="${esc50(old?.notes||'')}"></div><div class="row" style="grid-column:1/-1"><button class="primary">Зберегти</button><button type="button" class="secondary" onclick="closeModal()">Скасувати</button></div></form>`);$('movement50').onsubmit=async e=>{e.preventDefault();try{await saveMovement50(Object.fromEntries(new FormData(e.target)),id);closeModal()}catch(err){alert('Не вдалося зберегти рух птиці: '+(err?.message||err))}}};
window.deleteMovement50=async function(id){if(!confirm('Видалити рух птиці?'))return;const q=await db.from('livestock_events').delete().eq('id',id).eq('user_id',user.id);if(q.error)return alert('Не вдалося видалити рух: '+q.error.message);await load()};
function render50(){document.querySelectorAll('[data-movement47],[data-mv47]').forEach(x=>x.remove());document.querySelectorAll('#modalBody').forEach(root=>{const old47=root.querySelector('[data-movement47]');if(old47)old47.remove();const txt=(root.innerText||'').toLowerCase();const m=(root.innerHTML||'').match(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i);if(!m||!/бройлер|несуч|рух птиц|вибраку|продаж|додому|падіж/.test(txt))return;const bid=m[0],b=(C.batches||[]).find(x=>String(x.id)===String(bid));if(!b||root.querySelector('[data-movement50]'))return;const box=document.createElement('div');box.dataset.movement50='1';box.className='card section';const rows=ev50(bid).sort((a,z)=>String(z.event_date).localeCompare(String(a.event_date)));box.innerHTML=`<div class="row"><div><h3 style="margin:0">🐔 Рух птиці</h3><div class="muted">Залишок: <b>${balance50(bid)} гол.</b> · Початково: ${n50(b.initial_heads)} гол.</div></div><button class="primary noPrint" type="button" data-add50="1">＋ Додати рух</button></div><div style="overflow:auto;margin-top:10px"><table class="table"><thead><tr><th>Дата</th><th>Операція</th><th>Гол.</th><th>Маса</th><th>Сума</th><th>Дії</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc50(x.event_date)}</td><td>${TYPES50[x.event_type]||esc50(x.event_type)}</td><td>${n50(x.heads)}</td><td>${n50(x.weight_kg).toFixed(3)} кг</td><td>${n50(x.total_amount).toFixed(2)} грн</td><td><button class="secondary small" type="button" data-edit50="${x.id}">Ред.</button> <button class="danger small" type="button" data-del50="${x.id}">Видалити</button></td></tr>`).join('')||'<tr><td colspan="6">Рухів ще немає.</td></tr>'}</tbody></table></div>`;root.appendChild(box);box.querySelector('[data-add50]').onclick=()=>openMovement50(bid);box.querySelectorAll('[data-edit50]').forEach(x=>x.onclick=()=>openMovement50(bid,x.dataset.edit50));box.querySelectorAll('[data-del50]').forEach(x=>x.onclick=()=>deleteMovement50(x.dataset.del50))})}
const mo50=new MutationObserver(()=>{if(window.__fp50busy)return;window.__fp50busy=true;setTimeout(()=>{try{render50()}finally{window.__fp50busy=false}},40)});if(document.body)mo50.observe(document.body,{childList:true,subtree:true});setTimeout(render50,300);
document.addEventListener('submit',ev=>{const f=ev.target;if(!f||f.id==='movement50'||f.dataset.v50)return;const root=f.closest('#modalBody');const txt=(root?.innerText||'').toLowerCase();if(!/вибраку|вибракуван|рух птиц|продаж|додому|падіж|cull/.test(txt)||!f.querySelector('[name="heads"],#heads'))return;const m=(root.innerHTML||'').match(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i);if(!m)return;ev.preventDefault();ev.stopImmediatePropagation();f.dataset.v50='1';const bid=String(f.querySelector('[name="batch_id"]')?.value||m[0]);const p=Object.fromEntries(new FormData(f));p.batch_id=bid;saveMovement50(p,null).then(()=>closeModal()).catch(e=>alert('Помилка руху птиці: '+(e?.message||e)) )},true);
})();