(()=>{'use strict';
/* FERMA PRO v49: replace legacy bird movement/culling handlers with one schema-safe ledger. */
const n49=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const TYPES49={mortality:'Падіж',sale:'Продаж',home:'Додому',cull:'Вибракування',adjustment:'Коригування'};
const ev49=bid=>(C.events||[]).filter(x=>String(x.batch_id)===String(bid));
function signed49(x){const t=String(x.event_type||'');if(['mortality','sale','home','cull'].includes(t))return -n49(x.heads);if(t==='adjustment'){const s=String(x.notes||'').toLowerCase();return /(^|\s)(in|прихід|додано|додав)/.test(s)?n49(x.heads):-n49(x.heads)}return 0}
function balance49(bid,ignoreId){const b=(C.batches||[]).find(x=>String(x.id)===String(bid));if(!b)return 0;return Math.max(0,Math.round(n49(b.initial_heads)+ev49(bid).filter(x=>String(x.id)!==String(ignoreId)).reduce((s,x)=>s+signed49(x),0)))}
function payload49(f,bid){const p=Object.fromEntries(new FormData(f));p.batch_id=bid;p.event_type=String(p.event_type||'').trim();p.event_date=String(p.event_date||D()).slice(0,10);p.heads=Math.max(1,Math.round(n49(p.heads)));p.weight_kg=Math.max(0,n49(p.weight_kg));p.price_per_kg=Math.max(0,n49(p.price_per_kg));p.total_amount=Math.max(0,n49(p.total_amount));delete p.total_preview;if(p.event_type==='sale'&&p.total_amount<=0)p.total_amount=p.weight_kg*p.price_per_kg;return p}
window.saveMovement49=async function(p,id){if(!user||!db)throw new Error('Сесія користувача не готова');const x={...p};delete x.total_preview;x.heads=Math.max(1,Math.round(n49(x.heads)));x.weight_kg=Math.max(0,n49(x.weight_kg));x.price_per_kg=Math.max(0,n49(x.price_per_kg));x.total_amount=Math.max(0,n49(x.total_amount));if(x.event_type==='sale'&&x.total_amount<=0)x.total_amount=x.weight_kg*x.price_per_kg;x.event_date=String(x.event_date||D()).slice(0,10);if(!x.batch_id)throw new Error('Не вказано партію');if(!TYPES49[x.event_type])throw new Error('Невідомий тип операції');const available=balance49(x.batch_id,id);if(x.event_type!=='adjustment'&&x.heads>available)throw new Error(`Недостатньо птиці. Доступно: ${available} гол.`);const q=id?await db.from('livestock_events').update(x).eq('id',id).eq('user_id',user.id).select('*').single():await db.from('livestock_events').insert({...x,user_id:user.id}).select('*').single();if(q.error)throw q.error;await load();return q.data};
window.openMovement49=function(bid,id){const b=(C.batches||[]).find(x=>String(x.id)===String(bid));if(!b)return;const old=id?(C.events||[]).find(x=>String(x.id)===String(id)):null;const available=balance49(bid,id);openModal(`<h3>🐔 ${old?'Редагування руху':'Рух птиці'}: ${E(b.name)}</h3><p class="muted">Доступно зараз: <b>${available} гол.</b></p><form id="movement49" class="grid g2"><div class="field"><label>Дата</label><input name="event_date" type="date" value="${E(old?.event_date||D())}" required></div><div class="field"><label>Операція</label><select name="event_type"><option value="sale" ${old?.event_type==='sale'?'selected':''}>Продаж</option><option value="mortality" ${old?.event_type==='mortality'?'selected':''}>Падіж</option><option value="cull" ${old?.event_type==='cull'?'selected':''}>Вибракування</option><option value="home" ${old?.event_type==='home'?'selected':''}>Додому</option><option value="adjustment" ${old?.event_type==='adjustment'?'selected':''}>Коригування</option></select></div><div class="field"><label>Кількість, гол.</label><input name="heads" type="number" min="1" step="1" value="${n49(old?.heads)||1}" required></div><div class="field"><label>Маса, кг</label><input name="weight_kg" type="number" min="0" step="0.001" value="${n49(old?.weight_kg)}"></div><div class="field"><label>Ціна, грн/кг</label><input name="price_per_kg" type="number" min="0" step="0.01" value="${n49(old?.price_per_kg)}"></div><div class="field"><label>Сума, грн</label><input name="total_amount" type="number" min="0" step="0.01" value="${n49(old?.total_amount)}"></div><div class="field"><label>Клієнт</label><input name="client" value="${E(old?.client||'')}"></div><div class="field"><label>Примітка</label><input name="notes" value="${E(old?.notes||'')}"></div><div class="row" style="grid-column:1/-1"><button class="primary">Зберегти</button><button type="button" class="secondary" onclick="closeModal()">Скасувати</button></div></form>`);$('movement49').onsubmit=async e=>{e.preventDefault();try{await saveMovement49(payload49(e.target,bid),id);closeModal()}catch(err){alert('Не вдалося зберегти рух птиці: '+(err?.message||err))}}};
window.deleteMovement49=async function(id){if(!confirm('Видалити рух птиці?'))return;const q=await db.from('livestock_events').delete().eq('id',id).eq('user_id',user.id);if(q.error)return alert('Не вдалося видалити рух: '+q.error.message);await load()};
function render49(){document.querySelectorAll('[data-movement47]').forEach(x=>x.remove());const roots=[...document.querySelectorAll('#modalBody')];for(const root of roots){const txt=(root.innerText||'').toLowerCase();const m=(root.innerHTML||'').match(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i);if(!m||!/бройлер|несуч|рух птиц|вибраку|продаж/.test(txt))continue;const bid=m[0],b=(C.batches||[]).find(x=>String(x.id)===String(bid));if(!b)continue;if(root.querySelector('[data-movement49]'))continue;const box=document.createElement('div');box.dataset.movement49='1';box.className='card section';const rows=ev49(bid).sort((a,z)=>String(z.event_date).localeCompare(String(a.event_date)));box.innerHTML=`<div class="row"><div><h3 style="margin:0">🐔 Рух птиці</h3><div class="muted">Залишок: <b>${balance49(bid)} гол.</b> · Початково: ${n49(b.initial_heads)} гол.</div></div><button class="primary noPrint" type="button" id="addMovement49">＋ Додати рух</button></div><div style="overflow:auto;margin-top:10px"><table class="table"><thead><tr><th>Дата</th><th>Операція</th><th>Гол.</th><th>Маса</th><th>Сума</th><th>Дії</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${E(x.event_date)}</td><td>${TYPES49[x.event_type]||E(x.event_type)}</td><td>${n49(x.heads)}</td><td>${n49(x.weight_kg).toFixed(3)} кг</td><td>${n49(x.total_amount).toFixed(2)} грн</td><td><button class="secondary small" type="button" data-edit49="${x.id}">Ред.</button> <button class="danger small" type="button" data-del49="${x.id}">Видалити</button></td></tr>`).join('')||'<tr><td colspan="6">Рухів ще немає.</td></tr>'}</tbody></table></div>`;root.appendChild(box);$('addMovement49').onclick=()=>openMovement49(bid);box.querySelectorAll('[data-edit49]').forEach(x=>x.onclick=()=>openMovement49(bid,x.dataset.edit49));box.querySelectorAll('[data-del49]').forEach(x=>x.onclick=()=>deleteMovement49(x.dataset.del49))}}
const mo49=new MutationObserver(()=>setTimeout(render49,20));if(document.body)mo49.observe(document.body,{childList:true,subtree:true});setTimeout(render49,500);
/* Stop legacy submit handlers for movement/culling forms. v49 writes only total_amount, never total_preview. */
document.addEventListener('submit',ev=>{const f=ev.target;if(!f||f.dataset.v49)return;const root=f.closest('#modalBody');const txt=(root?.innerText||'').toLowerCase();if(!/вибраку|вибракуван|рух птиц|продаж|додому|падіж|cull/.test(txt))return;if(!f.querySelector('[name="heads"],#heads'))return;const m=(root.innerHTML||'').match(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i);if(!m)return;ev.preventDefault();ev.stopImmediatePropagation();f.dataset.v49='1';try{const bid=String(f.querySelector('[name="batch_id"]')?.value||m[0]);saveMovement49(payload49(f,bid)).then(()=>{closeModal()}).catch(e=>alert('Помилка руху птиці: '+(e?.message||e)))}catch(e){alert('Помилка руху птиці: '+(e?.message||e))}},true);
})();
