(()=>{'use strict';
const n25h=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const auto25h=(prefix,id)=>C.moves.filter(m=>m.user_id===user.id&&String(m.notes||'')===`${prefix}:${id}`);
async function restore25h(m){
 const p={user_id:user.id,item_id:m.item_id,movement_date:m.movement_date,movement_type:m.movement_type,quantity:n25h(m.quantity),unit_price:n25h(m.unit_price),total_amount:n25h(m.total_amount),adjustment_direction:m.adjustment_direction||null,batch_id:m.batch_id||null,reference_id:m.reference_id||null,supplier:m.supplier||null,notes:m.notes||null};
 const r=await db.from('warehouse_movements').insert(p); return !r.error;
}
async function replaceAuto25h(prefix,id,newItemId,newQty,date,unitPrice,batchId){
 const oldMoves=auto25h(prefix,id);
 const oldIds=new Set(oldMoves.map(m=>m.id));
 if(newItemId&&newQty>0){
   const stock=C.moves.filter(m=>m.item_id===newItemId&&!oldIds.has(m.id)).reduce((s,m)=>s+(m.movement_type==='in'||(m.movement_type==='adjustment'&&m.adjustment_direction==='in')?n25h(m.quantity):-n25h(m.quantity)),0);
   if(newQty>stock)throw new Error(`Недостатньо товару на складі. Доступно: ${stock}, потрібно: ${newQty}`);
 }
 const removed=[];
 for(const m of oldMoves){
   const r=await db.from('warehouse_movements').delete().eq('id',m.id).eq('user_id',user.id);
   if(r.error){for(const gone of removed)await restore25h(gone);throw new Error('Не вдалося безпечно замінити складський рух: '+r.error.message)}
   removed.push(m);
 }
 if(newItemId&&newQty>0){
   const r=await db.from('warehouse_movements').insert({user_id:user.id,item_id:newItemId,movement_date:date,movement_type:'use',quantity:newQty,unit_price:n25h(unitPrice),total_amount:n25h(newQty)*n25h(unitPrice),batch_id:batchId,notes:`${prefix}:${id}`});
   if(r.error){for(const gone of removed)await restore25h(gone);throw new Error('Не вдалося записати новий складський рух: '+r.error.message)}
 }
}
window.dailyForm=function(bid,id){
 const x=id?C.daily.find(d=>d.id===id):null,feeds=C.items.filter(i=>i.item_type==='feed'),oldMoves= id?auto25h('AUTO_FEED',id):[];
 const old=oldMoves[0]||null; const form=document.createElement('form');
 form.innerHTML=`<div class="grid"><label>Дата<input name="record_date" type="date" value="${x?.record_date||new Date().toISOString().slice(0,10)}"></label><label>Корм, кг<input name="feed_kg" type="number" step="0.01" value="${x?.feed_kg??''}"></label><label>Корм зі складу<select name="feed_item_id"><option value="">Не списувати автоматично</option>${feeds.map(i=>`<option value="${i.id}" ${(x?.feed_item_id||old?.item_id)===i.id?'selected':''}>${i.name} (${i.unit||'кг'})</option>`).join('')}</select></label><label>Ціна корму, грн/кг<input name="feed_price" type="number" step="0.01" value="${x?.feed_price??old?.unit_price??''}"></label><label>Вода, л<input name="water_l" type="number" step="0.01" value="${x?.water_l??''}"></label><label>Вода, грн<input name="water_cost" type="number" step="0.01" value="${x?.water_cost??''}"></label><label>Ліки, грн<input name="medicine_cost" type="number" step="0.01" value="${x?.medicine_cost??''}"></label><label>Підстилка, грн<input name="bedding_cost" type="number" step="0.01" value="${x?.bedding_cost??''}"></label><label>Електроенергія, грн<input name="electricity_cost" type="number" step="0.01" value="${x?.electricity_cost??''}"></label><label>Праця, грн<input name="labor_cost" type="number" step="0.01" value="${x?.labor_cost??''}"></label><label>Інші витрати, грн<input name="other_cost" type="number" step="0.01" value="${x?.other_cost??''}"></label><label>Примітка<input name="notes" value="${x?.notes||''}"></label></div><button>Зберегти</button> <button type="button" onclick="closeModal()">Скасувати</button>`;
 form.onsubmit=async e=>{e.preventDefault();const f=form;const itemId=f.feed_item_id.value||null,qty=n25h(f.feed_kg.value),price=n25h(f.feed_price.value);const p={batch_id:bid,record_date:f.record_date.value,feed_kg:qty,feed_item_id:itemId,water_l:n25h(f.water_l.value),water_cost:n25h(f.water_cost.value),medicine_cost:n25h(f.medicine_cost.value),bedding_cost:n25h(f.bedding_cost.value),electricity_cost:n25h(f.electricity_cost.value),labor_cost:n25h(f.labor_cost.value),other_cost:n25h(f.other_cost.value),notes:f.notes.value||null};try{if(!id){const r=await db.from('daily_records').insert({...p,user_id:user.id}).select('id').single();if(r.error)throw new Error(r.error.message);if(itemId&&qty>0)try{await replaceAuto25h('AUTO_FEED',r.data.id,itemId,qty,f.record_date.value,price,bid)}catch(err){await db.from('daily_records').delete().eq('id',r.data.id).eq('user_id',user.id);throw err}}else{const before={...x};const r=await db.from('daily_records').update(p).eq('id',id).eq('user_id',user.id);if(r.error)throw new Error(r.error.message);try{await replaceAuto25h('AUTO_FEED',id,itemId,qty,f.record_date.value,price,bid)}catch(err){await db.from('daily_records').update(before).eq('id',id).eq('user_id',user.id);throw err}}await load();closeModal();openBatch(bid)}catch(err){alert(err.message)}};
 document.getElementById('modalBody').innerHTML='';document.getElementById('modalBody').appendChild(form);document.getElementById('modal').classList.add('show');
};
window.treatForm=function(bid,id){
 const x=id?C.treat.find(t=>t.id===id):null,meds=C.items.filter(i=>i.item_type==='medicine'),oldMoves=id?auto25h('AUTO_MED',id):[];const old=oldMoves[0]||null;const form=document.createElement('form');
 form.innerHTML=`<div class="grid"><label>Дата<input name="treatment_date" type="date" value="${x?.treatment_date||new Date().toISOString().slice(0,10)}"></label><label>Препарат<select name="medicine_item_id"><option value="">Без списання зі складу</option>${meds.map(i=>`<option value="${i.id}" ${(x?.medicine_item_id||old?.item_id)===i.id?'selected':''}>${i.name}${i.concentration?' '+i.concentration:''}</option>`).join('')}</select></label><label>Назва препарату<input name="medicine_name" value="${x?.medicine_name||''}"></label><label>Дозування<input name="dosage" value="${x?.dosage||''}"></label><label>Птиця<input name="birds" type="number" value="${x?.birds??''}"></label><label>Використано, мл/г<input name="used_qty" type="number" step="0.01" value="${x?.used_qty??''}"></label><label>Ціна за 10 мл/г<input name="price10" type="number" step="0.01" value="${x?.price_per_unit?x.price_per_unit*10:old?.unit_price??''}"></label><label>Примітка<input name="notes" value="${x?.notes||''}"></label></div><button>Зберегти</button> <button type="button" onclick="closeModal()">Скасувати</button>`;
 form.onsubmit=async e=>{e.preventDefault();const f=form,itemId=f.medicine_item_id.value||null,qty=n25h(f.used_qty.value),price10=n25h(f.price10.value),unitPrice=price10/10;const selected=C.items.find(i=>i.id===itemId);const p={batch_id:bid,treatment_date:f.treatment_date.value,medicine_item_id:itemId,medicine_name:f.medicine_name.value||(selected?.name||''),dosage:f.dosage.value,birds:Math.round(n25h(f.birds.value)),used_qty:qty,unit:'ml',price_per_unit:unitPrice,total_cost:qty*unitPrice,notes:f.notes.value||null};try{if(!id){const r=await db.from('treatments').insert({...p,user_id:user.id}).select('id').single();if(r.error)throw new Error(r.error.message);if(itemId&&qty>0)try{await replaceAuto25h('AUTO_MED',r.data.id,itemId,qty,f.treatment_date.value,unitPrice,bid)}catch(err){await db.from('treatments').delete().eq('id',r.data.id).eq('user_id',user.id);throw err}}else{const before={...x};const r=await db.from('treatments').update(p).eq('id',id).eq('user_id',user.id);if(r.error)throw new Error(r.error.message);try{await replaceAuto25h('AUTO_MED',id,itemId,qty,f.treatment_date.value,unitPrice,bid)}catch(err){await db.from('treatments').update(before).eq('id',id).eq('user_id',user.id);throw err}}await load();closeModal();openBatch(bid)}catch(err){alert(err.message)}};
 document.getElementById('modalBody').innerHTML='';document.getElementById('modalBody').appendChild(form);document.getElementById('modal').classList.add('show');
};
})();