(()=>{'use strict';
/* FERMA PRO v47: reliable bird movement ledger + culling compatibility */
const n47=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const d47=v=>String(v||'').slice(0,10);
const TYPES47={mortality:'Падіж',sale:'Продаж',home:'Додому',cull:'Вибракування',adjustment:'Коригування'};
function events47(bid){return (C.events||[]).filter(x=>x.batch_id===bid)}
function balance47(bid){const b=(C.batches||[]).find(x=>x.id===bid);if(!b)return 0;return Math.max(0,n47(b.initial_heads)-events47(bid).filter(x=>x.event_type!=='adjustment').reduce((s,x)=>s+n47(x.heads),0)+events47(bid).filter(x=>x.event_type==='adjustment').reduce((s,x)=>s+(String(x.notes||'').toLowerCase().includes('in')?n47(x.heads):-n47(x.heads)),0))}
function clean47(p){const x={...(p||{})};if(x.total_preview!==undefined&&x.total_amount===undefined)x.total_amount=n47(x.total_preview);delete x.total_preview;x.heads=Math.max(1,Math.round(n47(x.heads)));x.weight_kg=Math.max(0,n47(x.weight_kg));x.price_per_kg=Math.max(0,n47(x.price_per_kg));x.total_amount=Math.max(0,n47(x.total_amount));x.event_date=d47(x.event_date)||D();return x}
window.saveLivestockEvent47=async function(payload,id){if(!user||!db)throw new Error('Сесія користувача не готова');const p=clean47(payload);if(!p.batch_id)throw new Error('Не вказано партію');if(!TYPES47[p.event_type])throw new Error('Невідомий тип руху птиці');const available=balance47(p.batch_id);if(!id&&p.event_type!=='adjustment'&&p.heads>available)throw new Error(`Недостатньо птиці. Доступно: ${available} гол.`);if(p.event_type==='sale'&&p.total_amount<=0&&p.weight_kg>0&&p.price_per_kg>0)p.total_amount=p.weight_kg*p.price_per_kg;let r=id?await db.from('livestock_events').update(p).eq('id',id).eq('user_id',user.id).select('*').single():await db.from('livestock_events').insert({...p,user_id:user.id}).select('*').single();if(r.error)throw r.error;await load();return r.data};
window.birdMovement47=async function(bid,id){const x=id?(C.events||[]).find(e=>e.id===id):null;const b=(C.batches||[]).find(z=>z.id===bid);if(!b)return;const av=balance47(bid);openModal(`<h3>${x?'Редагування':'Рух птиці'}: ${E(b.name)}</h3><p class="muted">Залишок у партії: <b>${av} гол.</b></p><form id="birdMove47" class="grid g2"><div class="field"><label>Дата</label><input name="event_date" type="date" value="${E(x?.event_date||D())}" required></div><div class="field"><label>Операція</label><select name="event_type"><option value="sale" ${x?.event_type==='sale'?'selected':''}>Продаж</option><option value="mortality" ${x?.event_type==='mortality'?'selected':''}>Падіж</option><option value="cull" ${x?.event_type==='cull'?'selected':''}>Вибракування</option><option value="home" ${x?.event_type==='home'?'selected':''}>Додому</option><option value="adjustment" ${x?.event_type==='adjustment'?'selected':''}>Коригування</option></select></div><div class="field"><label>Кількість, гол.</label><input name="heads" type="number" min="1" step="1" value="${n47(x?.heads)||1}" required></div><div class="field"><label>Маса, кг</label><input name="weight_kg" type="number" min="0" step="0.001" value="${n47(x?.weight_kg)}"></div><div class="field"><label>Ціна, грн/кг</label><input name="price_per_kg" type="number" min="0" step="0.01" value="${n47(x?.price_per_kg)}"></div><div class="field"><label>Сума, грн</label><input name="total_amount" type="number" min="0" step="0.01" value="${n47(x?.total_amount)}"></div><div class="field"><label>Клієнт</label><input name="client" value="${E(x?.client||'')}"></div><div class="field"><label>Примітка</label><input name="notes" value="${E(x?.notes||'')}"></div><div class="row" style="grid-column:1/-1"><button class="primary">Зберегти</button><button type="button" class="secondary" onclick="closeModal()">Скасувати</button></div></form>`);$('birdMove47').onsubmit=async e=>{e.preventDefault();try{const p=Object.fromEntries(new FormData(e.target));p.batch_id=bid;await saveLivestockEvent47(p,id);closeModal();alert('Рух птиці збережено.')}catch(err){alert('Не вдалося зберегти рух птиці: '+(err?.message||err))}}};
window.deleteBirdMovement47=async function(id){if(!confirm('Видалити цей рух птиці?'))return;const r=await db.from('livestock_events').delete().eq('id',id).eq('user_id',user.id);if(r.error)return alert(r.error.message);await load()};
function inject47(){const root=$('modalBody');if(!root||root.dataset.mv47)return;const html=root.innerHTML||'';const m=html.match(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i);if(!m)return;const bid=m[0];const b=(C.batches||[]).find(x=>x.id===bid);if(!b)return;root.dataset.mv47='1';const ev=events47(bid).sort((a,z)=>String(z.event_date).localeCompare(String(a.event_date)));const box=document.createElement('div');box.className='card section';box.innerHTML=`<div class="row"><div><h3 style="margin:0">🐔 Рух птиці</h3><div class="muted">Залишок: <b>${balance47(bid)} гол.</b> · Початково: ${n47(b.initial_heads)} гол.</div></div><button class="primary noPrint" type="button" id="addMove47">＋ Додати рух</button></div><div style="overflow:auto;margin-top:10px"><table class="table"><thead><tr><th>Дата</th><th>Операція</th><th>Гол.</th><th>Маса</th><th>Сума</th><th></th></tr></thead><tbody>${ev.map(x=>`<tr><td>${E(x.event_date)}</td><td>${TYPES47[x.event_type]||E(x.event_type)}</td><td>${n47(x.heads)}</td><td>${n47(x.weight_kg).toFixed(3)} кг</td><td>${n47(x.total_amount).toFixed(2)} грн</td><td><button class="secondary small" type="button" data-edit47="${x.id}">Ред.</button> <button class="danger small" type="button" data-del47="${x.id}">×</button></td></tr>`).join('')||'<tr><td colspan="6">Рухів ще немає.</td></tr>'}</tbody></table></div>`;root.appendChild(box);$('addMove47').onclick=()=>birdMovement47(bid);box.querySelectorAll('[data-edit47]').forEach(btn=>btn.onclick=()=>birdMovement47(bid,btn.dataset.edit47));box.querySelectorAll('[data-del47]').forEach(btn=>btn.onclick=()=>deleteBirdMovement47(btn.dataset.del47))}
const mo47=new MutationObserver(()=>setTimeout(inject47,0));if(document.body)mo47.observe(document.body,{childList:true,subtree:true});setInterval(()=>{try{inject47()}catch(e){console.error(e)}},800);
/* Capture legacy culling forms before old handlers submit a nonexistent total_preview column. */
document.addEventListener('submit',async function(ev){const f=ev.target;if(!f||f.dataset.v47capture)return;const txt=(f.closest('#modalBody')?.innerText||'').toLowerCase();if(!/вибраку|вибракуван|cull/.test(txt))return;const has= f.querySelector('[name="heads"],#heads');if(!has)return;ev.preventDefault();ev.stopImmediatePropagation();f.dataset.v47capture='1';try{const p=Object.fromEntries(new FormData(f));const bid=p.batch_id||((f.innerHTML||'').match(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i)||[])[0];p.batch_id=bid;p.event_type='cull';await saveLivestockEvent47(p);closeModal();alert('Вибракування збережено.')}catch(e){alert('Помилка при вибракуванні бройлера: '+(e?.message||e))}},true);
})();