(()=>{'use strict';
/* FERMA PRO v61: ADMIN shop management. Client-facing data stays isolated in shop_* tables with RLS. */
const esc61=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num61=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const money61=v=>num61(v).toLocaleString('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2})+' грн';
const oldRender61=window.render;
let shopAdminPage61=false;
async function shopAdmin61(){shopAdminPage61=true;const [pr,or]=await Promise.all([
 db.from('shop_products').select('*').order('sort_order').order('name'),
 db.from('shop_orders').select('*').order('created_at',{ascending:false})
]);
 const products=pr.data||[],orders=or.data||[];
 $('content').innerHTML=`<div class="row"><button class="primary" onclick="shopProductForm61()">＋ Додати товар</button><button class="secondary" onclick="shopAdmin61()">↻ Оновити</button><span class="pill">Товарів: ${products.length}</span><span class="pill">Замовлень: ${orders.filter(x=>x.status!=='completed'&&x.status!=='cancelled').length}</span></div>
 <div class="section card"><h3>🛒 Товари магазину</h3><table class="table"><thead><tr><th>Товар</th><th>Ціна</th><th>Наявність</th><th>Статус</th><th></th></tr></thead><tbody>${products.map(p=>`<tr><td><b>${esc61(p.name)}</b><br><span class="muted">${esc61(p.category||'')} · ${esc61(p.unit)}</span></td><td>${money61(p.price)}</td><td>${num61(p.stock_qty)} ${esc61(p.unit)}</td><td>${p.is_active?'Активний':'Прихований'}</td><td class="actions"><button class="secondary small" onclick="shopProductForm61('${p.id}')">Редагувати</button> <button class="danger small" onclick="shopToggle61('${p.id}',${!p.is_active})">${p.is_active?'Приховати':'Показати'}</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">Додайте перший товар.</td></tr>'}</tbody></table></div>
 <div class="section card"><h3>📦 Замовлення клієнтів</h3><table class="table"><thead><tr><th>Дата</th><th>Клієнт</th><th>Сума</th><th>Статус</th><th></th></tr></thead><tbody>${orders.map(o=>`<tr><td>${new Date(o.created_at).toLocaleString('uk-UA')}</td><td><b>${esc61(o.customer_name)}</b><br>${esc61(o.phone)}<br><span class="muted">${esc61(o.delivery_address||'')}</span></td><td><b>${money61(o.total_amount)}</b></td><td><select onchange="shopStatus61('${o.id}',this.value)">${['new','confirmed','processing','ready','completed','cancelled'].map(s=>`<option value="${s}" ${s===o.status?'selected':''}>${shopStatusName61(s)}</option>`).join('')}</select></td><td><button class="secondary small" onclick="shopOrder61('${o.id}')">Деталі</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">Замовлень немає.</td></tr>'}</tbody></table></div>`}
function shopStatusName61(s){return ({new:'Нове',confirmed:'Підтверджено',processing:'В обробці',ready:'Готово',completed:'Виконано',cancelled:'Скасовано'})[s]||s}
window.shopProductForm61=async id=>{let p=null;if(id){const r=await db.from('shop_products').select('*').eq('id',id).single();p=r.data}openModal(`<h3>${id?'Редагувати товар':'Новий товар'}</h3><form id="shopProductForm61" class="grid g2"><div class="field"><label>Назва</label><input name="name" required value="${esc61(p?.name||'')}"></div><div class="field"><label>Категорія</label><input name="category" value="${esc61(p?.category||'')}"></div><div class="field"><label>Ціна, грн</label><input name="price" type="number" min="0" step="0.01" value="${num61(p?.price)}"></div><div class="field"><label>Одиниця</label><input name="unit" value="${esc61(p?.unit||'кг')}"></div><div class="field"><label>Наявність</label><input name="stock_qty" type="number" min="0" step="0.001" value="${num61(p?.stock_qty)}"></div><div class="field"><label>Порядок</label><input name="sort_order" type="number" step="1" value="${num61(p?.sort_order)}"></div><div class="field" style="grid-column:1/-1"><label>Посилання на фото</label><input name="image_url" value="${esc61(p?.image_url||'')}"></div><div class="field" style="grid-column:1/-1"><label>Опис</label><textarea name="description">${esc61(p?.description||'')}</textarea></div><div><button class="primary">Зберегти</button> <button type="button" class="secondary" onclick="closeModal()">Скасувати</button></div></form>`);$('shopProductForm61').onsubmit=async e=>{e.preventDefault();const f=e.target;const payload={name:f.name.value.trim(),category:f.category.value.trim(),price:num61(f.price.value),unit:f.unit.value.trim()||'кг',stock_qty:num61(f.stock_qty.value),sort_order:Math.round(num61(f.sort_order.value)),image_url:f.image_url.value.trim(),description:f.description.value.trim(),updated_at:new Date().toISOString()};const r=id?await db.from('shop_products').update(payload).eq('id',id):await db.from('shop_products').insert(payload);if(r.error)return alert(r.error.message);closeModal();shopAdmin61()}}
window.shopToggle61=async(id,active)=>{const r=await db.from('shop_products').update({is_active:active,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)alert(r.error.message);else shopAdmin61()};
window.shopStatus61=async(id,status)=>{const r=await db.from('shop_orders').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)alert(r.error.message);else shopAdmin61()};
window.shopOrder61=async id=>{const [o,i]=await Promise.all([db.from('shop_orders').select('*').eq('id',id).single(),db.from('shop_order_items').select('*').eq('order_id',id)]);const x=o.data;openModal(`<h3>Замовлення #${esc61(id.slice(0,8))}</h3><p><b>${esc61(x.customer_name)}</b><br>${esc61(x.phone)}<br>${esc61(x.delivery_address||'')}</p>${(i.data||[]).map(a=>`<div class="card" style="margin:7px 0"><div class="row"><b>${esc61(a.product_name)}</b><span class="right">${money61(a.line_total)}</span></div><span class="muted">${a.quantity} ${esc61(a.unit)} × ${money61(a.unit_price)}</span></div>`).join('')}<h3>Разом: ${money61(x.total_amount)}</h3>${x.comment?`<p class="muted">${esc61(x.comment)}</p>`:''}<button class="secondary" onclick="closeModal()">Закрити</button>`)};
window.render=function(){if(window.current==='shop'){shopAdmin61();return}shopAdminPage61=false;return oldRender61.apply(this,arguments)};
if($('content')&&document.querySelector('.nav')){const nav=document.querySelector('.nav');if(!nav.querySelector('[data-page="shop"]')){const b=document.createElement('button');b.dataset.page='shop';b.textContent='🛒 Магазин';b.onclick=()=>{window.current='shop';window.render()};const settings=nav.querySelector('[data-page="settings"]');nav.insertBefore(b,settings||nav.lastElementChild)}if(!document.querySelector('.shop-title-placeholder')){}}
})();