(()=>{'use strict';
/* FERMA PRO livestock + finance accounting hardening */
const n6=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const decTypes=new Set(['mortality','sale','home','cull']);
window.heads=function(b){let n=n6(b?.initial_heads);if(!b)return 0;for(const x of C.events.filter(e=>e.batch_id===b.id)){if(decTypes.has(x.event_type))n-=n6(x.heads);else if(x.event_type==='adjustment')n+=n6(x.heads)}return Math.max(0,Math.round(n))};
window.birdSales=function(id){return C.events.filter(x=>x.batch_id===id&&x.event_type==='sale').reduce((s,x)=>{const total=n6(x.total_amount);return s+(total||n6(x.weight_kg)*n6(x.price_per_kg))},0)};
window.eggSalesIncome=function(id){return C.eggSales.filter(x=>x.batch_id===id).reduce((s,x)=>s+(n6(x.total_amount)||n6(x.quantity)*n6(x.price_per_egg)),0)};
window.income=function(id){return birdSales(id)+eggSalesIncome(id)+C.fin.filter(x=>x.batch_id===id&&x.operation_type==='income').reduce((s,x)=>s+n6(x.amount),0)};
window.totalCost=function(id){const b=batch(id);return n6(b?.initial_heads)*n6(b?.chick_price)+n6(window.feedCost(id))+n6(dailyCost(id))+n6(treatmentCost(id))+n6(explicitExpense(id))};
window.eventForm=function(bid,id){const x=id?C.events.find(e=>e.id===id):null;const types=[['mortality','Падіж'],['sale','Продаж'],['home','Додому'],['cull','Вибракування'],['adjustment','Коригування']];openModal(`<h3>${x?'Редагування':'Додати'} рух птиці</h3><form id="form" class="grid g2"><div class="field"><label>Дата</label><input name="event_date" type="date" value="${x?.event_date||D()}" required></div><div class="field"><label>Тип</label><select name="event_type" required>${types.map(t=>`<option value="${t[0]}" ${x?.event_type===t[0]?'selected':''}>${t[1]}</option>`).join('')}</select></div><div class="field"><label>Кількість голів</label><input name="heads" type="number" min="0" step="1" value="${x?Math.abs(n6(x.heads)):''}" required></div><div class="field"><label>Загальна маса, кг</label><input name="weight_kg" type="number" min="0" step=".001" value="${n6(x?.weight_kg)||''}"></div><div class="field"><label>Ціна за кг, грн</label><input name="price_per_kg" type="number" min="0" step=".01" value="${n6(x?.price_per_kg)||''}"></div><div class="field"><label>Клієнт</label><input name="client" value="${E(x?.client||'')}"></div><div class="field" style="grid-column:1/-1"><label>Примітка</label><input name="notes" value="${E(x?.notes||'')}"></div><button class="primary">Зберегти</button></form>`);$('form').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));p.batch_id=bid;p.heads=n6(p.heads);p.weight_kg=n6(p.weight_kg);p.price_per_kg=n6(p.price_per_kg);p.total_amount=p.event_type==='sale'?p.weight_kg*p.price_per_kg:0;if(p.event_type==='adjustment')p.heads=n6(p.heads);const b=batch(bid);let available=heads(b)+(x&&decTypes.has(x.event_type)?n6(x.heads):0);if(decTypes.has(p.event_type)&&p.heads>available)return alert(`Недостатньо птиці. Доступно: ${available} гол.`);if(p.event_type==='sale'&&p.weight_kg<=0)return alert('Для продажу вкажіть загальну масу.');if(p.event_type==='sale'&&p.price_per_kg<0)return alert('Ціна не може бути від’ємною.');if(await save('livestock_events',p,id)){closeModal();openBatch(bid)}}};
};
})();
