(()=>{'use strict';
/* FERMA PRO v54: force recipe editor to use warehouse_items directly. */
const n54=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const esc54=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt54=v=>n54(v).toLocaleString('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2});
async function warehouse54(){
 try{const r=await db.from('warehouse_items').select('id,name,price_per_unit,unit,item_type').order('name');if(r.error)throw r.error;return r.data||[]}catch(e){console.error('FERMA v54 warehouse load',e);return Array.isArray(C.items)?C.items:[]}
}
async function price54(id){
 try{const r=await db.from('warehouse_items').select('id,name,price_per_unit,unit,item_type').eq('id',id).maybeSingle();if(r.error)throw r.error;return r.data||null}catch(e){console.error('FERMA v54 warehouse item',e);return null}
}
function row54(x={},items=[]){const id=x.item_id||'',p=n54(x.price_per_kg);return `<div class="recipe54-line card" style="margin:8px 0;padding:10px"><div class="grid g3"><div class="field"><label>Інгредієнт зі складу</label><select class="r54-item" name="item_id" required><option value="">Оберіть інгредієнт</option>${items.map(i=>`<option value="${esc54(i.id)}" ${String(i.id)===String(id)?'selected':''}>${esc54(i.name)}</option>`).join('')}</select><small class="muted r54-stock">Оберіть інгредієнт</small></div><div class="field"><label>Кількість, кг</label><input class="r54-kg" name="kg" type="number" min=".001" step=".001" required value="${x.kg?n54(x.kg):''}"></div><div class="field"><label>Ціна зі складу, грн/кг</label><input class="r54-price" name="price_per_kg" type="number" readonly value="${p>0?p:''}" style="background:#f3f4f6;font-weight:700"><small class="muted r54-label">${p>0?fmt54(p)+' грн/кг':'Підтягується зі складу автоматично'}</small></div></div><div class="row"><span class="pill r54-cost">Вартість: 0.00 грн</span><button type="button" class="danger small r54-remove">× Видалити</button></div></div>`}
function calc54(f){if(!f)return;let kg=0,cost=0;f.querySelectorAll('.recipe54-line').forEach(r=>{const q=n54(r.querySelector('.r54-kg')?.value),p=n54(r.querySelector('.r54-price')?.value),c=q*p;kg+=q;cost+=c;const o=r.querySelector('.r54-cost');if(o)o.textContent='Вартість: '+fmt54(c)+' грн'});const s=f.querySelector('.r54-summary');if(s)s.textContent='Разом: '+kg.toFixed(3)+' кг • '+(kg?fmt54(cost/kg):'0.00')+' грн/кг • '+fmt54(cost)+' грн'}
async function sync54(r){const s=r.querySelector('.r54-item'),p=r.querySelector('.r54-price'),lab=r.querySelector('.r54-label'),st=r.querySelector('.r54-stock');if(!s||!p||!s.value){if(p)p.value='';if(lab)lab.textContent='Підтягується зі складу автоматично';return}const d=await price54(s.value),v=n54(d?.price_per_unit);p.value=v>0?String(v):'';if(lab)lab.textContent=v>0?fmt54(v)+' грн/кг':'На складі не задана ціна';if(st)st.textContent=d?'Склад: '+d.name+' • Ціна за од.: '+fmt54(v)+' грн':'Інгредієнт не знайдено на складі';calc54(r.closest('form'))}
async function open54(id){const items=await warehouse54();const r=id?C.recipes.find(x=>String(x.id)===String(id)):null;const lines=id?C.lines.filter(x=>String(x.recipe_id)===String(id)):[{}];openModal(`<h3>${r?'Редагувати':'Новий'} рецепт</h3><form id="recipeForm54"><div class="grid g2"><div class="field"><label>Назва рецепту</label><input name="name" required value="${esc54(r?.name||'')}"></div><div class="field"><label>Фаза</label><input name="phase" value="${esc54(r?.phase||'')}"></div></div><div id="recipeLines54" class="section">${(lines.length?lines:[{}]).map(x=>row54(x,items)).join('')}</div><div class="row"><button type="button" class="secondary" id="addR54">＋ Інгредієнт</button><span class="pill r54-summary">Разом: 0.000 кг • 0.00 грн/кг • 0.00 грн</span></div><p class="muted">🔒 Ціна не вводиться вручну. Вона береться безпосередньо з <b>Склад → Ціна за од.</b>.</p><div class="row"><button type="button" class="secondary" onclick="closeModal()">Скасувати</button><button class="primary">Зберегти рецепт</button></div></form>`);const f=$('recipeForm54');if(!f)return;const bind=rw=>{rw.querySelector('.r54-item')?.addEventListener('change',()=>sync54(rw));rw.querySelector('.r54-kg')?.addEventListener('input',()=>calc54(f));rw.querySelector('.r54-remove')?.addEventListener('click',()=>{rw.remove();calc54(f)});sync54(rw)};f.querySelectorAll('.recipe54-line').forEach(bind);$('addR54').onclick=()=>{const box=$('recipeLines54');box.insertAdjacentHTML('beforeend',row54({},items));bind(box.lastElementChild)};f.onsubmit=async e=>{e.preventDefault();const name=f.elements.name.value.trim();const rows=[];for(const rw of f.querySelectorAll('.recipe54-line')){const itemId=rw.querySelector('.r54-item').value,q=n54(rw.querySelector('.r54-kg').value);if(!itemId||q<=0)continue;const d=await price54(itemId),p=n54(d?.price_per_unit);if(!d||p<=0)return alert('Для «'+(d?.name||'інгредієнта')+'» не задана ціна на складі.');rows.push({item_id:itemId,ingredient_name:d.name,kg:q,price_per_kg:p})}if(!name)return alert('Вкажіть назву рецепту');if(!rows.length)return alert('Додайте інгредієнти з кількістю');let rr;if(id){const u=await db.from('feed_recipes').update({name,phase:f.elements.phase.value.trim()}).eq('id',id).eq('user_id',user.id).select().single();if(u.error)return alert(u.error.message);rr=u.data}else{const u=await db.from('feed_recipes').insert({name,phase:f.elements.phase.value.trim(),user_id:user.id}).select().single();if(u.error)return alert(u.error.message);rr=u.data}const d=await db.from('feed_recipe_lines').delete().eq('recipe_id',rr.id).eq('user_id',user.id);if(d.error)return alert(d.error.message);const ins=await db.from('feed_recipe_lines').insert(rows.map(x=>({...x,recipe_id:rr.id,user_id:user.id})));if(ins.error)return alert(ins.error.message);await load();closeModal()};calc54(f)}
function redirect54(){document.querySelectorAll('[onclick*="recipeForm"]')?.forEach(b=>{const oc=b.getAttribute('onclick')||'';const m=oc.match(/recipeForm\s*\(\s*['"]([^'"]*)['"]\s*\)/);if(m)b.setAttribute('onclick',`openRecipeWarehouse54('${m[1]}')`);else if(/recipeForm\s*\(\s*\)/.test(oc))b.setAttribute('onclick','openRecipeWarehouse54()')})}
window.openRecipeWarehouse54=open54;window.recipeForm=open54;setTimeout(redirect54,50);setTimeout(redirect54,500);new MutationObserver(()=>redirect54()).observe(document.body,{childList:true,subtree:true});
})();