(()=>{'use strict';
/* FERMA PRO v51: hard isolate layer feed recommendations from all broiler recipes. */
const bad51=/\b(starter|grower|finisher|finish)\b|бройлер|фінішний|фінішер/i;
const esc51=v=>typeof E==='function'?E(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const layerPhase51=b=>{if(!b||b.kind!=='layer')return null;const d=typeof age==='function'?Math.max(1,Number(age(b))||1):1;return d<140?{kind:'layer',name:'Вирощування',from_day:1,to_day:140}:{kind:'layer',name:'Кладка',from_day:140,to_day:9999}};
window.phaseFor=function(b){if(b?.kind==='layer')return layerPhase51(b);const d=typeof age==='function'?Math.max(1,Number(age(b))||1):1;return (C.phases||[]).filter(x=>x.kind===b?.kind).find(x=>d>=Number(x.from_day||0)&&d<=Number(x.to_day||999999))||null};
function activeLayer51(){const root=document.querySelector('#modalBody');const html=(root?.innerText||'')+' '+(document.querySelector('#content')?.innerText||'');if(!/несуч|кладка|вирощування/.test(html.toLowerCase()))return null;const m=(root?.innerHTML||'').match(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i);if(m){const b=(C.batches||[]).find(x=>String(x.id)===m[0]);if(b?.kind==='layer')return b}return (C.batches||[]).find(x=>x.kind==='layer'&&((root?.innerText||'').includes(x.name)||(document.querySelector('#content')?.innerText||'').includes(x.name)))||null}
function purge51(root){if(!root)return;root.querySelectorAll('select option').forEach(o=>{if(bad51.test(o.textContent||''))o.remove()});const candidates=[...root.querySelectorAll('*')].filter(el=>bad51.test(el.textContent||'')&&!([...el.children].some(ch=>bad51.test(ch.textContent||''))));for(const el of candidates){const t=(el.textContent||'').trim();if(t.length<=220)el.remove();else el.style.display='none'}}
function enforce51(){const b=activeLayer51();if(!b)return;purge51(document.querySelector('#modalBody'));purge51(document.querySelector('#content'));const root=document.querySelector('#modalBody');if(!root)return;const phase=layerPhase51(b),recipes=(C.recipes||[]).filter(r=>{const p=String(r.phase||'').trim();return p===phase.name&&!bad51.test(String(r.name||''))});let box=root.querySelector('[data-layerhard51]');if(!box){box=document.createElement('div');box.dataset.layerhard51='1';box.className='card section';root.appendChild(box)}box.innerHTML=`<h3>🌾 Рекомендований корм для несучок</h3><p class="muted">Фаза: <b>${esc51(phase.name)}</b> · ${phase.from_day}–${phase.to_day===9999?'140+':phase.to_day} день</p>${recipes.length?`<div><b>Рецепти цієї фази:</b><ul>${recipes.map(r=>`<li>${esc51(r.name)}</li>`).join('')}</ul></div>`:'<p class="muted">Рецепт для цієї фази ще не створений.</p>'}<p class="muted" style="margin-bottom:0">STARTER, GROWER та FINISHER бройлерів для несучок не використовуються.</p>`}
const oldOpen51=window.openBatch;if(typeof oldOpen51==='function')window.openBatch=function(id){const r=oldOpen51(id);let i=0;const t=setInterval(()=>{enforce51();if(++i>15)clearInterval(t)},100);return r};
const oldRender51=window.render;if(typeof oldRender51==='function')window.render=function(){const r=oldRender51();setTimeout(enforce51,80);return r};
const mo51=new MutationObserver(()=>{if(window.__fp51)return;window.__fp51=true;setTimeout(()=>{try{enforce51()}finally{window.__fp51=false}},30)});if(document.body)mo51.observe(document.body,{childList:true,subtree:true});setTimeout(enforce51,700);
})();