(()=>{'use strict';
/* FERMA PRO v39: recipes. Warehouse price is authoritative. */
const n39=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const esc39=v=>typeof E==='function'?E(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm39=v=>String(v??'').trim().toLowerCase().replace(/\s+/g,' ');
const forbidden39=/підкислювач|подкислитель|вотермінт|watermint/i;
const whItem39=id=>(C.items||[]).find(i=>String(i.id)===String(id));
const whByName39=name=>(C.items||[]).find(i=>norm39(i.name)===norm39(name));
const whPrice39=(id,name)=>n39((whItem39(id)||whByName39(name))?.price_per_unit);
window.recipeForm=async function(id){
 const r=id?C.recipes.find(x=>x.id===id):null;
 const lines=r?C.lines.filter(x=>x.recipe_id===id&&!forbidden39.test(String(x.ingredient_name||''))):[];
 const feeds=(C.items||[]).filter(i=>i.item_type==='feed'&&!forbidden39.test(String(i.name||'')));
 if(!feeds.length)return alert('Спочатку додайте інгредієнти корму на склад.');
 const row=x=>{const item=whItem39(x?.item_id)||whByName39(x?.ingredient_name)||feeds[0];const p=whPrice39(item?.id,item?.name);return `<tr class="recipe39"><td><select class="ri39" required>${feeds.map(i=>`<option value="${esc39(i.id)}" ${String(i.id)===String(item?.id)?'selected':''}>${esc39(i.name)}</option>`).join('')}</select></td><td><input class="kg39" type="number" min="0.001" step="0.001" value="${n39(x?.kg)||''}" required></td><td><input class="pr39" type="number" min="0" step="0.0001" value="${p||''}" readonly required title="Ціна автоматично зі складу"><small class="muted"> зі складу</small></td><td><input class="prot39" type="number" min="0" step="0.01" value="${n39(x?.protein_pct)||''}"></td><td><button type="button" class="danger small" onclick="this.closest('tr').remove()">×</button></td></tr>`};
 const layerOptions='<option value="Вирощування 1–140 день">Несучки: вирощування 1–140 день</option><option value="Кладка 140+ день">Несучки: кладка 140+ день</option>';
 openModal(`<h3>${r?'Редагувати':'Новий'} рецепт корму</h3><form id="recipeForm39"><div class="grid g2"><div class="field"><label>Назва рецепта</label><input name="name" required value="${esc39(r?.name||'')}"></div><div class="field"><label>Фаза корму</label><select name="phase"><option value="">— Загальний рецепт —</option><option>Бройлери STARTER</option><option>Бройлери GROWER 1</option><option>Бройлери GROWER 2</option><option>Бройлери GROWER 3</option><option>Бройлери FINISHER 1</option><option>Бройлери FINISHER 2</option>${layerOptions}</select></div><div class="field" style="grid-column:1/-1"><label>Примітка</label><textarea name="notes">${esc39(r?.notes||'')}</textarea></div></div><div class="card" style="margin:12px 0;background:#f8fafc"><b>🥚 Фази корму несучок</b><div class="muted" style="margin-top:5px"><b>Вирощування 1–140 день</b> та <b>Кладка 140+ день</b>.</div></div><div class="row" style="margin:12px 0"><b>Інгредієнти</b><button type="button" class="secondary" id="addR39">＋ Інгредієнт</button></div><div style="overflow:auto"><table class="table"><thead><tr><th>Інгредієнт</th><th>кг</th><th>грн/кг</th><th>Білок %</th><th></th></tr></thead><tbody id="recipeLines39">${lines.map(row).join('')||row({})}</tbody></table></div><div class="row" style="margin-top:12px"><button class="primary">Зберегти рецепт</button><button type="button" class="secondary" onclick="closeModal()">Скасувати</button></div></form>`);
 const f=$('recipeForm39'),tbody=$('recipeLines39');f.phase.value=r?.phase||'';
 const syncPrice39=async tr=>{const s=tr.querySelector('.ri39'),p=tr.querySelector('.pr39');if(!s||!p)return;const o=s.options[s.selectedIndex];p.value='';const price=whPrice39(s.value,o?.textContent);if(price>0){p.value=String(price);return}try{const q=await db.from('warehouse_items').select('price_per_unit').eq('id',s.value).maybeSingle();if(!q.error&&q.data)p.value=String(n39(q.data.price_per_unit)||'')}catch(e){console.error('warehouse price',e)}};
 const bind39=tr=>{const s=tr.querySelector('.ri39');if(!s)return;s.onchange=()=>syncPrice39(tr);syncPrice39(tr)};
 tbody.querySelectorAll('tr.recipe39').forEach(bind39);
 $('addR39').onclick=()=>{tbody.insertAdjacentHTML('beforeend',row({}));bind39(tbody.lastElementChild)};
 f.onsubmit=async e=>{e.preventDefault();const p={name:String(f.name.value||'').trim(),phase:String(f.phase.value||'').trim()||null,notes:String(f.notes.value||'').trim()||null};if(!p.name)return alert('Вкажіть назву рецепта.');
  const rows=[...tbody.querySelectorAll('tr.recipe39')].map(tr=>{const s=tr.querySelector('.ri39'),o=s.options[s.selectedIndex],price=whPrice39(s.value,o?.textContent);return{item_id:s.value,ingredient_name:o?.textContent?.trim()||'',kg:n39(tr.querySelector('.kg39').value),price_per_kg:price,protein_pct:n39(tr.querySelector('.prot39').value),energy_mj:0}}).filter(x=>x.item_id&&x.kg>0&&!forbidden39.test(x.ingredient_name));
  if(!rows.length)return alert('Додайте хоча б один інгредієнт.');
  if(rows.some(x=>x.price_per_kg<=0))return alert('Для вибраного інгредієнта не знайдена ціна зі складу. Вкажіть ціну в Складі.');
  try{let recipeId=id;if(id){const u=await db.from('feed_recipes').update(p).eq('id',id).eq('user_id',user.id).select('id').single();if(u.error)throw u.error;recipeId=u.data.id;const d=await db.from('feed_recipe_lines').delete().eq('recipe_id',recipeId);if(d.error)throw d.error}else{const ins=await db.from('feed_recipes').insert({...p,user_id:user.id}).select('id').single();if(ins.error)throw ins.error;recipeId=ins.data.id}const insL=await db.from('feed_recipe_lines').insert(rows.map(x=>({...x,recipe_id:recipeId,user_id:user.id})));if(insL.error)throw insL.error;await load();closeModal();alert('Рецепт збережено.')}catch(err){console.error(err);alert('Не вдалося зберегти рецепт: '+(err?.message||err))}
 };
};
})();