(()=>{'use strict';
/* FERMA PRO v55: final hard override. Recipe prices are read from warehouse_items by id OR name. */
const N55=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const X55=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm55=v=>String(v??'').trim().toLowerCase().replace(/\s+/g,' ');
const fmt55=v=>N55(v).toLocaleString('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2});
async function all55(){try{const r=await db.from('warehouse_items').select('id,name,price_per_unit,unit,item_type').order('name');if(!r.error&&Array.isArray(r.data))return r.data}catch(e){console.error('v55 warehouse',e)}return Array.isArray(C.items)?C.items:[]}
async function one55(id,name){try{if(id){let r=await db.from('warehouse_items').select('id,name,price_per_unit,unit,item_type').eq('id',id).maybeSingle();if(!r.error&&r.data)return r.data}if(name){let r=await db.from('warehouse_items').select('id,name,price_per_unit,unit,item_type').ilike('name',String(name).trim()).limit(1);if(!r.error&&r.data?.[0])return r.data[0]}}catch(e){console.error('v55 price',e)}return null}
function rows55(items,lines){return (lines.length?lines:[{}]).map(x=>{const i=items.find(a=>String(a.id)===String(x.item_id))||items.find(a=>norm55(a.name)===norm55(x.ingredient_name));return `<div class="r55-line card" style="margin:8px 0;padding:10px" data-old-name="${X55(x.ingredient_name||'')}"><div class="grid g3"><div class="field"><label>Інгредієнт зі складу</label><select class="r55-item" required><option value="">Оберіть інгредієнт</option>${items.map(a=>`<option value="${X55(a.id)}" ${i&&String(a.id)===String(i.id)?'selected':''}>${X55(a.name)}</option>`).join('')}</select><small class="muted r55-info">Ціна береться зі складу</small></div><div class="field"><label>Кількість, кг</label><input class="r55-kg" type="number" min=".001" step=".001" required value="${x.kg?N55(x.kg):''}"></div><div class="field"><label>Ціна зі складу, грн/кг</label><input class="r55-price" type="number" readonly value="${N55(x.price_per_kg)>0?N55(x.price_per_kg):''}" style="background:#f3f4f6;font-weight:700"><small class="muted r55-label">${N55(x.price_per_kg)>0?fmt55(x.price_per_kg)+' грн/кг':'Виберіть інгредієнт'}</small></div></div><div class="row"><span class="pill r55-cost">Вартість: 0.00 грн</span><button type="button" class="danger small r55-del">× Видалити</button></div></div>`}).join('')}
function calc55(f){if(!f)return;let kg=0,c=0;f.querySelectorAll('.r55-line').forEach(r=>{const q=N55(r.querySelector('.r55-kg')?.value),p=N55(r.querySelector('.r55-price')?.value);kg+=q;c+=q*p;r.querySelector('.r55-cost').textContent='Вартість: '+fmt55(q*p)+' грн'});const s=f.querySelector('.r55-total');if(s)s.textContent='Разом: '+kg.toFixed(3)+' кг • '+(kg?fmt55(c/kg):'0.00')+' грн/кг • '+fmt55(c)+' грн'}
async function sync55(r){const s=r.querySelector('.r55-item'),p=r.querySelector('.r55-price'),lab=r.querySelector('.r55-label'),info=r.querySelector('.r55-info');if(!s||!p)return;const name=s.options[s.selectedIndex]?.text||'';if(!s.value){p.value='';lab.textContent='Виберіть інгредієнт';return}const d=await one55(s.value,name),v=N55(d?.price_per_unit);p.value=v>0?String(v):'';lab.textContent=v>0?fmt55(v)+' грн/кг':'Ціна не задана на складі';info.textContent=d?'Склад: '+d.name+' • Ціна за од.: '+fmt55(v)+' грн':'Не знайдено на складі';calc55(r.closest('form'))}
async function form55(id){const items=await all55(),r=id?C.recipes.find(x=>String(x.id)===String(id)):null,lines=id?C.lines.filter(x=>String(x.recipe_id)===String(id)):[];openModal(`<h3>${r?'Редагувати':'Новий'} рецепт</h3><form id="r55form"><div class="grid g2"><div class="field"><label>Назва рецепту</label><input name="name" required value="${X55(r?.name||'')}"></div><div class="field"><label>Фаза</label><input name="phase" value="${X55(r?.phase||'')}"></div></div><div id="r55lines" class="section">${rows55(items,lines)}</div><div class="row"><button type="button" class="secondary" id="r55add">＋ Інгредієнт</button><span class="pill r55-total">Разом: 0.000 кг • 0.00 грн/кг • 0.00 грн</span></div><p class="muted">🔒 Ціна вводиться тільки на сторінці <b>Склад</b>. У рецепті вона підтягується автоматично.</p><div class="row"><button type="button" class="secondary" onclick="closeModal()">Скасувати</button><button class="primary">Зберегти рецепт</button></div></form>`);const f=$('r55form');if(!f)return;const bind=rw=>{rw.querySelector('.r55-item').onchange=()=>sync55(rw);rw.querySelector('.r55-kg').oninput=()=>calc55(f);rw.querySelector('.r55-del').onclick=()=>{rw.remove();calc55(f)};sync55(rw)};f.querySelectorAll('.r55-line').forEach(bind);$('r55add').onclick=()=>{$('r55lines').insertAdjacentHTML('beforeend',rows55(items,[{}]));bind($('r55lines').lastElementChild)};f.onsubmit=async e=>{e.preventDefault();const name=f.elements.name.value.trim();if(!name)return alert('Вкажіть назву рецепту');const out=[];for(const rw of f.querySelectorAll('.r55-line')){const s=rw.querySelector('.r55-item'),q=N55(rw.querySelector('.r55-kg').value),nm=s.options[s.selectedIndex]?.text||'';if(!s.value||q<=0)continue;const d=await one55(s.value,nm),p=N55(d?.price_per_unit);if(!d||p<=0)return alert('Для «'+nm+'» не задана ціна на складі.');out.push({item_id:d.id,ingredient_name:d.name,kg:q,price_per_kg:p})}if(!out.length)return alert('Додайте інгредієнти з кількістю');let rr;if(id){const z=await db.from('feed_recipes').update({name,phase:f.elements.phase.value.trim()}).eq('id',id).eq('user_id',user.id).select().single();if(z.error)return alert(z.error.message);rr=z.data}else{const z=await db.from('feed_recipes').insert({name,phase:f.elements.phase.value.trim(),user_id:user.id}).select().single();if(z.error)return alert(z.error.message);rr=z.data}let z=await db.from('feed_recipe_lines').delete().eq('recipe_id',rr.id).eq('user_id',user.id);if(z.error)return alert(z.error.message);z=await db.from('feed_recipe_lines').insert(out.map(a=>({...a,recipe_id:rr.id,user_id:user.id})));if(z.error)return alert(z.error.message);await load();closeModal()};calc55(f)}
window.recipeForm=form55;window.openRecipeWarehouse55=form55;
document.addEventListener('click',e=>{const b=e.target.closest?.('[onclick]');if(!b)return;const oc=b.getAttribute('onclick')||'';const m=oc.match(/recipeForm\s*\(\s*(?:['"]([^'"]*)['"])?\s*\)/);if(!m)return;e.preventDefault();e.stopImmediatePropagation();form55(m[1]||null)},true);
setInterval(()=>{if(window.recipeForm!==form55)window.recipeForm=form55},300);
})();