(()=>{'use strict';
/* FERMA PRO: final accounting audit and layer production metrics */
const n22=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const money22=v=>n22(v).toLocaleString('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2});
window.homeFeedKg22=id=>C.moves.filter(m=>m.batch_id===id&&m.movement_type==='home'&&C.items.some(i=>i.id===m.item_id&&i.item_type==='feed')).reduce((s,m)=>s+n22(m.quantity),0);
window.homeFeedCost22=id=>C.moves.filter(m=>m.batch_id===id&&m.movement_type==='home'&&C.items.some(i=>i.id===m.item_id&&i.item_type==='feed')).reduce((s,m)=>s+(n22(m.total_amount)||n22(m.quantity)*n22(m.unit_price)),0);
window.accountingAudit22=function(batchId=null){const issues=[];const bs=C.batches.filter(b=>!batchId||b.id===batchId);bs.forEach(b=>{const id=b.id;const h=n22(heads(b));const initial=n22(b.initial_heads);if(h<0)issues.push(`${b.name}: негативне поголів'я`);if(h>initial+n22(C.events.filter(e=>e.batch_id===id&&e.event_type==='adjustment').reduce((s,e)=>s+n22(e.heads),0)))issues.push(`${b.name}: поголів'я перевищує допустиме`);const sold=n22(window.soldWeightKg?.(id));const home=n22(window.homeWeightKg?.(id));const cull=n22(window.cullWeightKg?.(id));const live=n22((typeof latestWeight==='function'?latestWeight(id):null)?.average_weight_g)*h/1000;if(sold<0||home<0||cull<0||live<0)issues.push(`${b.name}: некоректна маса`);const feed=n22(feedKg(id));if(feed<0)issues.push(`${b.name}: некоректна витрата корму`);if(b.kind==='layer'){const produced=n22(eggProduced(id)),eggsSold=n22(eggSold(id));if(eggsSold>produced)issues.push(`${b.name}: продано яєць більше, ніж вироблено`);C.eggSales.filter(x=>x.batch_id===id).forEach(s=>{const expected=n22(s.quantity)*n22(s.price_per_egg);if(Math.abs(expected-n22(s.total_amount))>.01)issues.push(`${b.name}: помилка суми продажу яєць`);});}});C.moves.filter(m=>(!batchId||m.batch_id===batchId)&&m.movement_type==='use').forEach(m=>{const bal=C.moves.filter(x=>x.item_id===m.item_id).reduce((s,x)=>s+(x.movement_type==='in'||(x.movement_type==='adjustment'&&x.adjustment_direction==='in')?n22(x.quantity):-n22(x.quantity)),0);if(bal<-.0001)issues.push(`Склад: від'ємний залишок для ${C.items.find(i=>i.id===m.item_id)?.name||'позиції'}`);});return [...new Set(issues)];};
window.layerAccounting22=id=>{const b=batch(id);if(!b||b.kind!=='layer')return null;const produced=n22(eggProduced(id)),sold=n22(eggSold(id)),available=Math.max(0,produced-sold),feed=n22(feedKg(id)),feedCost=n22(feedCost(id)),homeKg=n22(homeFeedKg22(id)),homeCost=n22(homeFeedCost22(id)),income=n22(income(id)),cost=n22(typeof totalCost==='function'?totalCost(id):0),result=income-cost;return {heads:n22(heads(b)),produced,sold,available,feedKg:feed,feedCost,homeFeedKg:homeKg,homeFeedCost:homeCost,income,cost,result,eggsPer100Hens:n22(heads(b))>0?produced/n22(heads(b))*100:0,feedPer100Eggs:produced>0?feed/produced*100:0,costPerEgg:produced>0?cost/produced:0,incomePerEgg:sold>0?income/sold:0};};
})();
