(()=>{'use strict';
/* FERMA PRO v60: force recipe phase to be a real dropdown, never a manual text input. */
const esc60=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num60=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const phaseText60=p=>String(p?.name??p?.phase??p?.title??((p?.from_day!=null||p?.to_day!=null)?`День ${p.from_day??''}-${p.to_day??''}`:'')).trim();
async function getPhases60(){
 let a=Array.isArray(C?.phases)?C.phases:[];
 if(!a.length){try{const r=await db.from('feed_phases').select('*').order('sort_order');if(!r.error)a=r.data||[]}catch(e){console.warn('v60 phases',e)}}
 return a.map(phaseText60).filter(Boolean).filter((v,i,x)=>x.findIndex(y=>y.toLowerCase()===v.toLowerCase())===i);
}
async function items60(){try{const r=await db.from('warehouse_items').select('id,name,price_per_unit,unit,item_type').order('name');if(!r.error)return r.data||[]}catch(e){}return Array.isArray(C?.items)?C.items:[]}
function line60(items,x={}){const found=items.find(i=>String(i.id)===String(x.item_id))||items.find(i=>String(i.name).toLowerCase()===String(x.ingredient_name||'').toLowerCase());return `<div class="r60-line card" style="margin:8px 0;padding:10px"><div class="grid g3"><div class="field"><label>Інгредієнт зі складу</label><select class="r60-item" required><option value="">Оберіть інгредієнт</option>${items.map(i=>`<option value="${esc60(i.id)}" ${found&&String(i.id)===String(found.id)?'selected':''}>${esc60(i.name)}</option>`).join('')}</select></div><div class="field"><label>Кількість, кг</label><input class="r60-kg" type="number" min=".001" step=".001" required value="${x.kg?num60(x.kg):''}"></div><div class="field"><label>Ціна, грн/кг</label><input class="r60-price" type="number" readonly value="${num60(x.price_per_kg)||''}"></div></div><div class="row"><span class="pill r60-cost">Вартість: 0.00 грн</span><button type="button" class="danger small r60-del">× Видалити</button></div></div>`}
async function edit60(id){
 const [items,phases]=await Promise.all([items60(),getPhases60()]);
 const r=id&&Array.isArray(C?.recipes)?C.recipes.find(x=>String(x.id)===String(id)):null;
 const lines=id&&Array.isArray(C?.lines)?C.lines.filter(x=>String(x.recipe_id)===String(id)):[];
 openModal(`<h3>${r?'Редагувати':'Новий'} рецепт</h3><form id="r60form"><div class="grid g2"><div class="field"><label>Назва рецепту</label><input name="name" required value="${esc60(r?.name||'')}"></div><div class="field"><label>Фаза корму</label><select name="phase" id="r60phase" required><option value="">Оберіть фазу корму</option>${phases.map(p=>`<option value="${esc60(p)}" ${String(p).toLowerCase()===String(r?.phase||'').toLowerCase()?'selected':''}>${esc60(p)}</option>`).join('')}</select>${!phases.length?'<small class="muted">Не знайдено жодної фази корму в feed_phases.</small>':''}</div></div><div id="r60lines">${(lines.length?lines:[{}]).map(x=>line60(items,x)).join('')}</div><div class="row"><button type="button" class="secondary" id="r60add">＋ Інгредієнт</button></div><div class="row"><button type="button" class="secondary" onclick="closeModal()">Скасувати</button><button class="primary">Зберегти рецепт</button></div></form>`);
 const f=$('r60form');if(!f)return;
 const bind=row=>{const s=row.querySelector('.r60-item'),q=row.querySelector('.r60-kg'),p=row.querySelector('.r60-price');s.onchange=async()=>{try{const z=await db.from('warehouse_items').select('price_per_unit').eq('id',s.value).maybeSingle();p.value=z.data?num60(z.data.price_per_unit):0}catch(e){p.value=0}};q.oninput=()=>row.querySelector('.r60-cost').textContent='Вартість: '+(num60(q.value)*num60(p.value)).toFixed(2)+' грн';row.querySelector('.r60-del').onclick=()=>row.remove();if(s.value)s.onchange()};
 f.querySelectorAll('.r60-line').forEach(bind);$('r60add').onclick=()=>{$('r60lines').insertAdjacentHTML('beforeend',line60(items,{}));bind($('r60lines').lastElementChild)};
 f.onsubmit=async e=>{e.preventDefault();const name=f.elements.name.value.trim(),phase=f.elements.phase.value;if(!name)return alert('Вкажіть назву рецепту');if(!phase)return alert('Оберіть фазу корму');const out=[];for(const row of f.querySelectorAll('.r60-line')){const s=row.querySelector('.r60-item'),q=num60(row.querySelector('.r60-kg').value);if(!s.value||q<=0)continue;const z=await db.from('warehouse_items').select('id,name,price_per_unit').eq('id',s.value).maybeSingle();if(z.error||!z.data)return alert('Інгредієнт не знайдений на складі');out.push({item_id:z.data.id,ingredient_name:z.data.name,kg:q,price_per_kg:num60(z.data.price_per_unit),recipe_id:id,user_id:user.id})}if(!out.length)return alert('Додайте інгредієнти з кількістю');let z;if(id){z=await db.from('feed_recipes').update({name,phase}).eq('id',id).eq('user_id',user.id)}else{z=await db.from('feed_recipes').insert({name,phase,user_id:user.id})}if(z.error)return alert(z.error.message);let rid=id;if(!rid){const q=await db.from('feed_recipes').select('id').eq('user_id',user.id).eq('name',name).eq('phase',phase).order('created_at',{ascending:false}).limit(1).maybeSingle();if(q.error||!q.data)return alert(q.error?.message||'Не вдалося отримати рецепт');rid=q.data.id}z=await db.from('feed_recipe_lines').delete().eq('recipe_id',rid).eq('user_id',user.id);if(z.error)return alert(z.error.message);z=await db.from('feed_recipe_lines').insert(out.map(x=>({...x,recipe_id:rid})));if(z.error)return alert(z.error.message);await load();closeModal()};
}
window.recipeForm=edit60;
const force60=()=>{const b=[...document.querySelectorAll('[onclick]')].find(x=>/recipeForm\s*\(/.test(x.getAttribute('onclick')||''));if(b&&!b.dataset.r60){b.dataset.r60='1';b.addEventListener('click',e=>{const oc=b.getAttribute('onclick')||'',m=oc.match(/recipeForm\s*\(\s*(?:['"]([^'"]*)['"])?/);e.preventDefault();e.stopImmediatePropagation();edit60(m?.[1]||null)},true)}};
force60();new MutationObserver(force60).observe(document.body,{subtree:true,childList:true});
})();