(()=>{'use strict';
/* FERMA PRO accounting hardening: egg sales + layer household feed */
const n5=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
window.eggSaleForm=function(bid,id){
 const x=id?C.eggSales.find(e=>e.id===id):null;
 openModal(`<h3>Продаж яєць</h3><form id="form" class="grid g2"><div class="field"><label>Дата</label><input name="sale_date" type="date" value="${x?.sale_date||D()}" required></div><div class="field"><label>Кількість</label><input name="quantity" type="number" min="1" value="${n5(x?.quantity)||''}" required></div><div class="field"><label>Ціна за яйце, грн</label><input name="price_per_egg" type="number" min="0" step=".01" value="${n5(x?.price_per_egg)||''}" required></div><div class="field"><label>Клієнт</label><input name="client" value="${E(x?.client||'')}"></div><div class="field" style="grid-column:1/-1"><label>Примітка</label><input name="notes" value="${E(x?.notes||'')}"></div><button class="primary">Зберегти</button></form>`);
 $('form').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));p.batch_id=bid;p.quantity=n5(p.quantity);p.price_per_egg=n5(p.price_per_egg);p.total_amount=p.quantity*p.price_per_egg;const avail=eggAvailable(bid)+(x?n5(x.quantity):0);if(p.quantity>avail)return alert('Недостатньо яєць на складі.');if(await save('egg_sales',p,id)){closeModal();openBatch(bid)}};
};
window.layerFeedHomeForm=function(bid,id){
 const x=id?C.moves.find(m=>m.id===id):null;const feeds=C.items.filter(i=>i.item_type==='feed');
 if(!feeds.length)return alert('Спочатку додайте корм на склад.');
 openModal(`<h3>Корм додому</h3><form id="form" class="grid g2"><div class="field"><label>Корм</label><select name="item_id" required>${feeds.map(i=>`<option value="${i.id}">${E(i.name)} (${E(i.unit)})</option>`).join('')}</select></div><div class="field"><label>Дата</label><input name="movement_date" type="date" value="${x?.movement_date||D()}" required></div><div class="field"><label>Кількість</label><input name="quantity" type="number" min=".001" step=".001" value="${n5(x?.quantity)||''}" required></div><div class="field"><label>Ціна за од., грн</label><input name="unit_price" type="number" min="0" step=".0001" value="${n5(x?.unit_price)}"></div><div class="field" style="grid-column:1/-1"><label>Примітка</label><input name="notes" value="${E(x?.notes||'Корм додому')}"></div><button class="primary">Зберегти</button></form>`);
 if(x)$('form').item_id.value=x.item_id;
 $('form').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));p.batch_id=bid;p.movement_type='home';p.quantity=n5(p.quantity);p.unit_price=n5(p.unit_price);p.total_amount=p.quantity*p.unit_price;const bal=C.moves.filter(m=>m.item_id===p.item_id&&m.id!==id).reduce((s,m)=>s+(m.movement_type==='in'||(m.movement_type==='adjustment'&&m.adjustment_direction==='in')?n5(m.quantity):-n5(m.quantity)),0);if(p.quantity>bal)return alert('Недостатньо корму на складі.');if(await save('warehouse_movements',p,id)){closeModal();openBatch(bid)}};
};
const originalTab5=window.tab;window.tab=function(id,t){originalTab5(id,t);if(t!=='daily')return;const b=batch(id);if(!b||b.kind!=='layer')return;const home=C.moves.filter(m=>m.batch_id===id&&m.movement_type==='home'&&C.items.find(i=>i.id===m.item_id)?.item_type==='feed').sort((a,b)=>new Date(a.movement_date)-new Date(b.movement_date));const total=home.reduce((s,m)=>s+n5(m.quantity),0);const box=document.createElement('div');box.className='card section';box.innerHTML=`<div class="row"><h3>🏠 Корм додому</h3><button class="primary right" onclick="layerFeedHomeForm('${id}')">＋ Додати</button></div><p>Всього вилучено: <b>${total.toFixed(3)} кг</b></p><table class="table"><tr><th>Дата</th><th>Корм</th><th>Кількість</th><th>Сума</th><th></th></tr>${home.map(m=>{const it=C.items.find(i=>i.id===m.item_id);return `<tr><td>${m.movement_date}</td><td>${E(it?.name||'')}</td><td>${n5(m.quantity).toFixed(3)} ${E(it?.unit||'')}</td><td>${M(n5(m.total_amount)||n5(m.quantity)*n5(m.unit_price))}</td><td><button class="secondary small" onclick="layerFeedHomeForm('${id}','${m.id}')">Ред.</button> <button class="danger small" onclick="del('warehouse_movements','${m.id}');setTimeout(()=>tab('${id}','daily'),300)">×</button></td></tr>`}).join('')||'<tr><td colspan="5">Немає вилучень корму додому</td></tr>'}</table>`;$('tabBody').appendChild(box)};
})();
